/**
 * 워드마스터 수능 2000 전체 데이터셋 (Day 01 ~ Day 50)
 * 총 50개 Day 세트, 각 40단어 (총 2,000단어)
 * 교재(폴더) 분류: book = "워드마스터 수능 2000"
 */
const WORDMASTER_2000_SETS = [
  {
    "id": "wm2000_day_01",
    "book": "워드마스터 수능 2000",
    "title": "Day 01",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "provide", "ko": "공급하다, 제공하다" },
      { "en": "develop", "ko": "개발하다, 발전하다" },
      { "en": "service", "ko": "서비스, 봉사" },
      { "en": "inform", "ko": "알리다, 통지하다" },
      { "en": "relationship", "ko": "관계" },
      { "en": "improve", "ko": "향상시키다, 개선하다" },
      { "en": "individual", "ko": "개인, 개인의" },
      { "en": "require", "ko": "필요로 하다, 요구하다" },
      { "en": "advise", "ko": "조언하다, 충고하다" },
      { "en": "social", "ko": "사회의, 사교적인" },
      { "en": "amount", "ko": "총액, 양" },
      { "en": "behave", "ko": "행동하다" },
      { "en": "employ", "ko": "고용하다, 쓰다" },
      { "en": "attitude", "ko": "태도, 입장" },
      { "en": "research", "ko": "연구, 연구하다" },
      { "en": "audience", "ko": "청중, 관객" },
      { "en": "volunteer", "ko": "자원봉사, 자원하다" },
      { "en": "influence", "ko": "영향, 영향을 끼치다" },
      { "en": "terrible", "ko": "끔찍한, 무서운" },
      { "en": "opportunity", "ko": "기회" },
      { "en": "ability", "ko": "능력" },
      { "en": "expense", "ko": "비용, 지출" },
      { "en": "local", "ko": "지방의, 지역의" },
      { "en": "involve", "ko": "포함하다, 관련되다" },
      { "en": "stress", "ko": "스트레스, 강조하다" },
      { "en": "therefore", "ko": "그러므로, 그 결과" },
      { "en": "positive", "ko": "긍정적인, 확신하는" },
      { "en": "average", "ko": "평균, 평균의" },
      { "en": "ride", "ko": "타다, 태워주기" },
      { "en": "encourage", "ko": "격려하다, 장려하다" },
      { "en": "determine", "ko": "결정하다, 결심하다" },
      { "en": "international", "ko": "국제의, 국제적인" },
      { "en": "consume", "ko": "소비하다, 먹다" },
      { "en": "impress", "ko": "깊은 인상을 주다" },
      { "en": "object", "ko": "물체, 목표, 반대하다" },
      { "en": "available", "ko": "이용 가능한, 시간이 있는" },
      { "en": "contain", "ko": "함유하다, 포함하다" },
      { "en": "recognize", "ko": "인지하다, 인정하다" },
      { "en": "material", "ko": "재료, 물질" },
      { "en": "comfort", "ko": "편안하게 하다, 위로하다" }
    ]
  },
  {
    "id": "wm2000_day_02",
    "book": "워드마스터 수능 2000",
    "title": "Day 02",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "emotion", "ko": "감정, 정서" },
      { "en": "amaze", "ko": "놀라게 하다" },
      { "en": "reduce", "ko": "줄이다, 감소시키다" },
      { "en": "discover", "ko": "발견하다" },
      { "en": "decide", "ko": "결정하다, 결심하다" },
      { "en": "benefit", "ko": "이익, 혜택을 주다" },
      { "en": "affect", "ko": "영향을 미치다" },
      { "en": "occur", "ko": "일어나다, 발생하다" },
      { "en": "complex", "ko": "복잡한, 복합건물" },
      { "en": "define", "ko": "정의하다, 규정하다" },
      { "en": "proud", "ko": "자랑스러워하는" },
      { "en": "aware", "ko": "알고 있는, 인지하는" },
      { "en": "contact", "ko": "접촉하다, 연락하다" },
      { "en": "profession", "ko": "직업, 전문직" },
      { "en": "detail", "ko": "세부사항, 상세히 설명하다" },
      { "en": "approach", "ko": "접근하다, 접근법" },
      { "en": "career", "ko": "경력, 직업" },
      { "en": "package", "ko": "소포, 꾸러미" },
      { "en": "disappear", "ko": "사라지다, 없어지다" },
      { "en": "novel", "ko": "소설, 참신한" },
      { "en": "secure", "ko": "안전한, 확보하다" },
      { "en": "fashion", "ko": "유행, 방식" },
      { "en": "despite", "ko": "~에도 불구하고" },
      { "en": "background", "ko": "배경" },
      { "en": "solution", "ko": "해결책, 용액" },
      { "en": "generate", "ko": "발생시키다, 생성하다" },
      { "en": "generation", "ko": "세대, 발생" },
      { "en": "separate", "ko": "분리하다, 떨어진" },
      { "en": "specify", "ko": "명시하다, 구체적으로 밝히다" },
      { "en": "extreme", "ko": "극단적인, 극심한" },
      { "en": "frequent", "ko": "빈번한, 잦은" },
      { "en": "regular", "ko": "규칙적인, 정기적인" },
      { "en": "continuous", "ko": "계속되는, 지속적인" },
      { "en": "general", "ko": "일반적인, 보통의" },
      { "en": "ancient", "ko": "고대의, 옛날의" },
      { "en": "unique", "ko": "독특한, 유일한" },
      { "en": "normal", "ko": "정상적인, 평범한" },
      { "en": "standard", "ko": "표준, 기준" },
      { "en": "typical", "ko": "전형적인, 대표적인" },
      { "en": "rare", "ko": "드문, 희귀한" }
    ]
  },
  {
    "id": "wm2000_day_03",
    "book": "워드마스터 수능 2000",
    "title": "Day 03",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "insist", "ko": "주장하다, 고집하다" },
      { "en": "due", "ko": "~할 예정인, 만기의" },
      { "en": "negative", "ko": "부정적인" },
      { "en": "athletic", "ko": "운동의, 체육의" },
      { "en": "factor", "ko": "요인, 요소" },
      { "en": "mental", "ko": "정신의, 마음의" },
      { "en": "imagine", "ko": "상상하다" },
      { "en": "tend", "ko": "~하는 경향이 있다" },
      { "en": "constant", "ko": "끊임없는, 일정한" },
      { "en": "replace", "ko": "대체하다, 바꾸다" },
      { "en": "activity", "ko": "활동" },
      { "en": "physical", "ko": "신체적인, 물질의" },
      { "en": "community", "ko": "지역 사회, 공동체" },
      { "en": "focus", "ko": "집중하다, 초점" },
      { "en": "variety", "ko": "다양성, 종류" },
      { "en": "various", "ko": "다양한" },
      { "en": "respond", "ko": "응답하다, 반응하다" },
      { "en": "response", "ko": "응답, 반응" },
      { "en": "prevent", "ko": "예방하다, 막다" },
      { "en": "create", "ko": "창조하다, 만들다" },
      { "en": "creativity", "ko": "창의성" },
      { "en": "creature", "ko": "생물, 생명체" },
      { "en": "manage", "ko": "관리하다, 해내다" },
      { "en": "management", "ko": "경영, 관리" },
      { "en": "current", "ko": "현재의, 흐름" },
      { "en": "currently", "ko": "현재, 지금" },
      { "en": "remove", "ko": "제거하다, 없애다" },
      { "en": "damage", "ko": "손상, 피해를 입히다" },
      { "en": "compete", "ko": "경쟁하다" },
      { "en": "competition", "ko": "경쟁, 대회" },
      { "en": "competitive", "ko": "경쟁력 있는" },
      { "en": "competitor", "ko": "경쟁자" },
      { "en": "observe", "ko": "관찰하다, 준수하다" },
      { "en": "observation", "ko": "관찰" },
      { "en": "produce", "ko": "생산하다, 농산물" },
      { "en": "product", "ko": "제품, 생산품" },
      { "en": "production", "ko": "생산" },
      { "en": "productive", "ko": "생산적인" },
      { "en": "productivity", "ko": "생산성" },
      { "en": "labor", "ko": "노동, 근로" }
    ]
  },
  {
    "id": "wm2000_day_04",
    "book": "워드마스터 수능 2000",
    "title": "Day 04",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "publish", "ko": "출판하다, 발표하다" },
      { "en": "aim", "ko": "목표, 겨냥하다" },
      { "en": "contemporary", "ko": "현대의, 동시대의" },
      { "en": "exhibit", "ko": "전시하다, 전시품" },
      { "en": "organize", "ko": "조직하다, 정리하다" },
      { "en": "organization", "ko": "조직, 단체" },
      { "en": "arrange", "ko": "배열하다, 준비하다" },
      { "en": "arrangement", "ko": "준비, 배열" },
      { "en": "participate", "ko": "참여하다, 참가하다" },
      { "en": "participation", "ko": "참여, 참가" },
      { "en": "participant", "ko": "참가자" },
      { "en": "accept", "ko": "받아들이다, 수락하다" },
      { "en": "acceptable", "ko": "용인되는, 받아들일 수 있는" },
      { "en": "acceptance", "ko": "수락, 수용" },
      { "en": "admit", "ko": "인정하다, 입장을 허락하다" },
      { "en": "admission", "ko": "입장료, 인정" },
      { "en": "permit", "ko": "허가하다, 허가증" },
      { "en": "permission", "ko": "허락, 허가" },
      { "en": "allow", "ko": "허락하다, 인정하다" },
      { "en": "forbid", "ko": "금지하다" },
      { "en": "prohibit", "ko": "금지하다, 막다" },
      { "en": "ban", "ko": "금지하다, 금지" },
      { "en": "limit", "ko": "제한하다, 한계" },
      { "en": "limitation", "ko": "한계, 제한" },
      { "en": "restrict", "ko": "제한하다, 통제하다" },
      { "en": "restriction", "ko": "제한, 규제" },
      { "en": "contain", "ko": "포함하다, 억누르다" },
      { "en": "container", "ko": "그릇, 용기" },
      { "en": "include", "ko": "포함하다" },
      { "en": "exclude", "ko": "배제하다, 제외하다" },
      { "en": "exclusive", "ko": "독점적인, 배타적인" },
      { "en": "consist", "ko": "구성되다" },
      { "en": "compose", "ko": "구성하다, 작곡하다" },
      { "en": "composition", "ko": "구성, 작문" },
      { "en": "constitute", "ko": "구성하다, 제정하다" },
      { "en": "constitution", "ko": "헌법, 구성" },
      { "en": "comprise", "ko": "구성하다, 차지하다" },
      { "en": "involvement", "ko": "관여, 개입" },
      { "en": "attach", "ko": "붙이다, 첨부하다" },
      { "en": "attachment", "ko": "부착물, 애착" }
    ]
  },
  {
    "id": "wm2000_day_05",
    "book": "워드마스터 수능 2000",
    "title": "Day 05",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "struggle", "ko": "투쟁하다, 분투하다" },
      { "en": "effort", "ko": "노력, 수고" },
      { "en": "attempt", "ko": "시도하다, 시도" },
      { "en": "challenge", "ko": "도전, 이의를 제기하다" },
      { "en": "overcome", "ko": "극복하다, 이겨내다" },
      { "en": "conquer", "ko": "정복하다, 극복하다" },
      { "en": "defeat", "ko": "패배시키다, 패배" },
      { "en": "surrender", "ko": "항복하다, 굴복하다" },
      { "en": "yield", "ko": "생산하다, 굴복하다, 양보하다" },
      { "en": "resist", "ko": "저항하다, 참다" },
      { "en": "resistance", "ko": "저항, 반대" },
      { "en": "endure", "ko": "견디다, 참다" },
      { "en": "endurance", "ko": "인내, 지구력" },
      { "en": "tolerate", "ko": "참다, 용인하다" },
      { "en": "tolerance", "ko": "관용, 내성" },
      { "en": "bear", "ko": "견디다, 낳다, 곰" },
      { "en": "withstand", "ko": "견뎌내다, 버티다" },
      { "en": "suffer", "ko": "고통받다, 겪다" },
      { "en": "suffering", "ko": "고통, 괴로움" },
      { "en": "pain", "ko": "고통, 통증" },
      { "en": "painful", "ko": "고통스러운" },
      { "en": "ache", "ko": "아프다, 통증" },
      { "en": "hurt", "ko": "다치게 하다, 아프다" },
      { "en": "injure", "ko": "부상을 입히다" },
      { "en": "injury", "ko": "부상, 상처" },
      { "en": "wound", "ko": "상처를 입히다, 부상" },
      { "en": "heal", "ko": "치료하다, 낫다" },
      { "en": "cure", "ko": "치료하다, 해결책" },
      { "en": "treat", "ko": "치료하다, 대우하다, 대접하다" },
      { "en": "treatment", "ko": "치료, 대우" },
      { "en": "remedy", "ko": "치료법, 해결책" },
      { "en": "therapy", "ko": "치료, 요법" },
      { "en": "therapist", "ko": "치료사" },
      { "en": "patient", "ko": "환자, 참을성 있는" },
      { "en": "patience", "ko": "인내심" },
      { "en": "impatient", "ko": "참을성 없는, 안달하는" },
      { "en": "nurse", "ko": "간호사, 돌보다" },
      { "en": "clinic", "ko": "진료소, 병원" },
      { "en": "hospital", "ko": "병원" },
      { "en": "ambulance", "ko": "구급차" }
    ]
  },
  {
    "id": "wm2000_day_06",
    "book": "워드마스터 수능 2000",
    "title": "Day 06",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "educate", "ko": "교육하다" },
      { "en": "education", "ko": "교육" },
      { "en": "educational", "ko": "교육의, 교육적인" },
      { "en": "instruct", "ko": "지시하다, 가르치다" },
      { "en": "instruction", "ko": "설명, 지시" },
      { "en": "instructor", "ko": "강사, 지도자" },
      { "en": "lecture", "ko": "강의, 강연하다" },
      { "en": "lecturer", "ko": "강연자, 강사" },
      { "en": "curriculum", "ko": "교육과정" },
      { "en": "major", "ko": "전공의, 주요한, 전공하다" },
      { "en": "minor", "ko": "부전공의, 사소한" },
      { "en": "degree", "ko": "학위, 정도, 도" },
      { "en": "diploma", "ko": "졸업장, 수료증" },
      { "en": "graduate", "ko": "졸업하다, 졸업생" },
      { "en": "graduation", "ko": "졸업" },
      { "en": "scholar", "ko": "학자" },
      { "en": "scholarship", "ko": "장학금, 학문" },
      { "en": "academic", "ko": "학업의, 학술적인" },
      { "en": "academy", "ko": "학원, 학술원" },
      { "en": "faculty", "ko": "교수진, 능력" },
      { "en": "tuition", "ko": "수업료, 등록금" },
      { "en": "semester", "ko": "학기" },
      { "en": "term", "ko": "학기, 용어, 조건" },
      { "en": "assignment", "ko": "과제, 배정" },
      { "en": "assign", "ko": "할당하다, 배정하다" },
      { "en": "submit", "ko": "제출하다, 굴복하다" },
      { "en": "submission", "ko": "제출, 굴복" },
      { "en": "evaluate", "ko": "평가하다" },
      { "en": "evaluation", "ko": "평가" },
      { "en": "assess", "ko": "평가하다, 사정하다" },
      { "en": "assessment", "ko": "평가, 사정" },
      { "en": "grade", "ko": "성적, 등급, 채점하다" },
      { "en": "score", "ko": "점수, 득점하다" },
      { "en": "exam", "ko": "시험, 검사" },
      { "en": "examine", "ko": "검사하다, 진찰하다" },
      { "en": "examination", "ko": "시험, 검사" },
      { "en": "knowledge", "ko": "지식" },
      { "en": "knowledgeable", "ko": "아는 것이 많은" },
      { "en": "wisdom", "ko": "지혜" },
      { "en": "intelligent", "ko": "지능이 있는, 똑똑한" }
    ]
  },
  {
    "id": "wm2000_day_07",
    "book": "워드마스터 수능 2000",
    "title": "Day 07",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "science", "ko": "과학" },
      { "en": "scientific", "ko": "과학의, 과학적인" },
      { "en": "scientist", "ko": "과학자" },
      { "en": "technology", "ko": "기술" },
      { "en": "technological", "ko": "기술적인" },
      { "en": "technical", "ko": "전문적인, 기술의" },
      { "en": "technique", "ko": "기법, 기술" },
      { "en": "experiment", "ko": "실험, 실험하다" },
      { "en": "experimental", "ko": "실험의, 실험적인" },
      { "en": "laboratory", "ko": "실험실, 연구소" },
      { "en": "hypothesis", "ko": "가설" },
      { "en": "theory", "ko": "이론" },
      { "en": "theoretical", "ko": "이론적인" },
      { "en": "formula", "ko": "공식, 제조법" },
      { "en": "variable", "ko": "변수, 변하기 쉬운" },
      { "en": "constant", "ko": "상수, 일정한" },
      { "en": "data", "ko": "자료, 데이터" },
      { "en": "datum", "ko": "자료 (단수)" },
      { "en": "analyze", "ko": "분석하다" },
      { "en": "analysis", "ko": "분석" },
      { "en": "analytic", "ko": "분석적인" },
      { "en": "invent", "ko": "발명하다" },
      { "en": "invention", "ko": "발명, 발명품" },
      { "en": "inventor", "ko": "발명가" },
      { "en": "innovate", "ko": "혁신하다" },
      { "en": "innovation", "ko": "혁신, 쇄신" },
      { "en": "innovative", "ko": "혁신적인" },
      { "en": "patent", "ko": "특허, 특허를 받다" },
      { "en": "discover", "ko": "발견하다" },
      { "en": "discovery", "ko": "발견" },
      { "en": "explore", "ko": "탐험하다, 탐구하다" },
      { "en": "exploration", "ko": "탐험, 탐구" },
      { "en": "investigate", "ko": "조사하다, 수사하다" },
      { "en": "investigation", "ko": "조사, 수사" },
      { "en": "detect", "ko": "감지하다, 발견하다" },
      { "en": "detection", "ko": "감지, 발견" },
      { "en": "detector", "ko": "탐지기" },
      { "en": "sensor", "ko": "감지기, 센서" },
      { "en": "device", "ko": "장치, 기기" },
      { "en": "instrument", "ko": "기구, 악기, 도구" }
    ]
  },
  {
    "id": "wm2000_day_08",
    "book": "워드마스터 수능 2000",
    "title": "Day 08",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "environment", "ko": "환경" },
      { "en": "environmental", "ko": "환경의, 환경적인" },
      { "en": "ecology", "ko": "생태학, 생태계" },
      { "en": "ecological", "ko": "생태학의" },
      { "en": "ecosystem", "ko": "생태계" },
      { "en": "habitat", "ko": "서식지" },
      { "en": "species", "ko": "종 (생물)" },
      { "en": "extinct", "ko": "멸종된" },
      { "en": "extinction", "ko": "멸종" },
      { "en": "endangered", "ko": "멸종 위기에 처한" },
      { "en": "preserve", "ko": "보존하다, 보호하다" },
      { "en": "preservation", "ko": "보존, 보호" },
      { "en": "conserve", "ko": "보존하다, 아끼다" },
      { "en": "conservation", "ko": "보호, 보존" },
      { "en": "protect", "ko": "보호하다" },
      { "en": "protection", "ko": "보호" },
      { "en": "protective", "ko": "보호하는" },
      { "en": "pollute", "ko": "오염시키다" },
      { "en": "pollution", "ko": "오염, 공해" },
      { "en": "pollutant", "ko": "오염 물질" },
      { "en": "contaminate", "ko": "오염시키다" },
      { "en": "contamination", "ko": "오염" },
      { "en": "waste", "ko": "쓰레기, 낭비하다" },
      { "en": "recycle", "ko": "재활용하다" },
      { "en": "recyclable", "ko": "재활용 가능한" },
      { "en": "garbage", "ko": "쓰레기" },
      { "en": "trash", "ko": "쓰레기" },
      { "en": "litter", "ko": "쓰레기를 버리다, 쓰레기" },
      { "en": "emission", "ko": "배출, 방출" },
      { "en": "emit", "ko": "방출하다, 내뿜다" },
      { "en": "climate", "ko": "기후" },
      { "en": "global", "ko": "지구의, 세계적인" },
      { "en": "warming", "ko": "온난화" },
      { "en": "drought", "ko": "가뭄" },
      { "en": "flood", "ko": "홍수, 범람하다" },
      { "en": "famine", "ko": "기근, 굶주림" },
      { "en": "disaster", "ko": "재앙, 재난" },
      { "en": "catastrophe", "ko": "대참사, 재앙" },
      { "en": "renewable", "ko": "재생 가능한" },
      { "en": "sustainable", "ko": "지속 가능한" }
    ]
  },
  {
    "id": "wm2000_day_09",
    "book": "워드마스터 수능 2000",
    "title": "Day 09",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "economy", "ko": "경제" },
      { "en": "economic", "ko": "경제의, 경제학의" },
      { "en": "economical", "ko": "경제적인, 절약하는" },
      { "en": "economics", "ko": "경제학" },
      { "en": "financially", "ko": "재정적으로" },
      { "en": "finance", "ko": "금융, 재정" },
      { "en": "fiscal", "ko": "재정의, 회계의" },
      { "en": "capital", "ko": "자본, 수도, 대문자" },
      { "en": "capitalism", "ko": "자본주의" },
      { "en": "invest", "ko": "투자하다" },
      { "en": "investment", "ko": "투자, 투자금" },
      { "en": "investor", "ko": "투자자" },
      { "en": "profit", "ko": "이익, 수익" },
      { "en": "profitable", "ko": "수익성이 있는" },
      { "en": "loss", "ko": "손실, 분실" },
      { "en": "revenue", "ko": "수익, 세입" },
      { "en": "income", "ko": "소득, 수입" },
      { "en": "outcome", "ko": "결과, 성과" },
      { "en": "budget", "ko": "예산, 예산을 세우다" },
      { "en": "fund", "ko": "자금, 기금" },
      { "en": "funding", "ko": "자금 지원" },
      { "en": "cost", "ko": "비용, 비용이 들다" },
      { "en": "price", "ko": "가격, 대가" },
      { "en": "charge", "ko": "요금, 청구하다, 충전하다" },
      { "en": "fee", "ko": "수수료, 요금" },
      { "en": "fare", "ko": "교통 요금" },
      { "en": "currency", "ko": "통화, 화폐" },
      { "en": "inflation", "ko": "인플레이션, 물가 상승" },
      { "en": "deflation", "ko": "디플레이션, 물가 하락" },
      { "en": "debt", "ko": "빚, 부채" },
      { "en": "loan", "ko": "대출, 빌려주다" },
      { "en": "borrow", "ko": "빌리다" },
      { "en": "lend", "ko": "빌려주다" },
      { "en": "bankrupt", "ko": "파산한" },
      { "en": "bankruptcy", "ko": "파산, 도산" },
      { "en": "trade", "ko": "무역, 거래하다" },
      { "en": "commerce", "ko": "상업, 통상" },
      { "en": "commercial", "ko": "상업의, 광고" },
      { "en": "market", "ko": "시장, 시장에 내놓다" },
      { "en": "merchandise", "ko": "상품, 물품" }
    ]
  },
  {
    "id": "wm2000_day_10",
    "book": "워드마스터 수능 2000",
    "title": "Day 10",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "society", "ko": "사회" },
      { "en": "sociology", "ko": "사회학" },
      { "en": "socialize", "ko": "사귀다, 사회화하다" },
      { "en": "politics", "ko": "정치, 정치학" },
      { "en": "political", "ko": "정치적인" },
      { "en": "politician", "ko": "정치인" },
      { "en": "government", "ko": "정부, 행정" },
      { "en": "govern", "ko": "통치하다, 지배하다" },
      { "en": "governor", "ko": "주지사, 통치자" },
      { "en": "state", "ko": "국가, 주, 상태, 말하다" },
      { "en": "nation", "ko": "국가, 민족" },
      { "en": "national", "ko": "국가의, 전국의" },
      { "en": "citizen", "ko": "시민, 국민" },
      { "en": "citizenship", "ko": "시민권" },
      { "en": "democracy", "ko": "민주주의" },
      { "en": "democratic", "ko": "민주적인" },
      { "en": "republic", "ko": "공화국" },
      { "en": "republican", "ko": "공화국의, 공화당원" },
      { "en": "monarchy", "ko": "군주제" },
      { "en": "dictator", "ko": "독재자" },
      { "en": "dictatorship", "ko": "독재 정권" },
      { "en": "law", "ko": "법, 법률" },
      { "en": "legal", "ko": "합법적인, 법률의" },
      { "en": "illegal", "ko": "불법의" },
      { "en": "court", "ko": "법원, 법정, 코트" },
      { "en": "judge", "ko": "판사, 판단하다" },
      { "en": "judgment", "ko": "판단, 판결" },
      { "en": "jury", "ko": "배심원단" },
      { "en": "trial", "ko": "재판, 시도, 시련" },
      { "en": "justice", "ko": "정의, 사법" },
      { "en": "injustice", "ko": "불의, 부정" },
      { "en": "crime", "ko": "범죄" },
      { "en": "criminal", "ko": "범죄자, 범죄의" },
      { "en": "victim", "ko": "피해자, 희생자" },
      { "en": "suspect", "ko": "용의자, 의심하다" },
      { "en": "arrest", "ko": "체포하다, 체포" },
      { "en": "punish", "ko": "처벌하다" },
      { "en": "punishment", "ko": "처벌, 형벌" },
      { "en": "penalty", "ko": "처벌, 벌금" },
      { "en": "fine", "ko": "벌금, 좋은, 미세한" }
    ]
  },
  {
    "id": "wm2000_day_11",
    "book": "워드마스터 수능 2000",
    "title": "Day 11",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "culture", "ko": "문화" },
      { "en": "cultural", "ko": "문화의" },
      { "en": "art", "ko": "예술, 미술, 기술" },
      { "en": "artist", "ko": "예술가, 화가" },
      { "en": "artistic", "ko": "예술적인" },
      { "en": "literature", "ko": "문학" },
      { "en": "literary", "ko": "문학의" },
      { "en": "literal", "ko": "글자 그대로의" },
      { "en": "literate", "ko": "읽고 쓸 줄 아는" },
      { "en": "illiterate", "ko": "문맹의" },
      { "en": "illiteracy", "ko": "문맹" },
      { "en": "masterpiece", "ko": "걸작, 명작" },
      { "en": "classic", "ko": "고전의, 대표적인, 명작" },
      { "en": "classical", "ko": "고전적인, 클래식의" },
      { "en": "heritage", "ko": "유산, 전통" },
      { "en": "tradition", "ko": "전통, 관습" },
      { "en": "traditional", "ko": "전통적인" },
      { "en": "custom", "ko": "관습, 풍습, 세관" },
      { "en": "customary", "ko": "관례적인" },
      { "en": "folklore", "ko": "민속, 민간전승" },
      { "en": "ritual", "ko": "의식, 의례" },
      { "en": "ceremony", "ko": "의식, 식" },
      { "en": "celebrate", "ko": "축하하다, 기념하다" },
      { "en": "celebration", "ko": "축하, 축제" },
      { "en": "festival", "ko": "축제, 페스티벌" },
      { "en": "performance", "ko": "공연, 성과, 실행" },
      { "en": "perform", "ko": "공연하다, 수행하다" },
      { "en": "performer", "ko": "공연자, 연기자" },
      { "en": "exhibition", "ko": "전시회" },
      { "en": "gallery", "ko": "미술관, 화랑" },
      { "en": "museum", "ko": "박물관" },
      { "en": "sculpture", "ko": "조각품, 조각" },
      { "en": "sculptor", "ko": "조각가" },
      { "en": "statue", "ko": "동상, 조각상" },
      { "en": "portrait", "ko": "초상화, 인물사진" },
      { "en": "landscape", "ko": "풍경, 풍경화" },
      { "en": "canvas", "ko": "캔버스, 화폭" },
      { "en": "palette", "ko": "팔레트" },
      { "en": "craft", "ko": "공예, 기술, 배" },
      { "en": "craftsman", "ko": "장인, 공예가" }
    ]
  },
  {
    "id": "wm2000_day_12",
    "book": "워드마스터 수능 2000",
    "title": "Day 12",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "psychology", "ko": "심리학" },
      { "en": "psychological", "ko": "심리적인, 정신적인" },
      { "en": "personality", "ko": "성격, 인성, 개성" },
      { "en": "character", "ko": "성격, 특징, 등장인물" },
      { "en": "characteristic", "ko": "특징적인, 특성" },
      { "en": "trait", "ko": "특성, 특색" },
      { "en": "temperament", "ko": "기질, 성품" },
      { "en": "mood", "ko": "기분, 분위기" },
      { "en": "temper", "ko": "성질, 성미, 누그러뜨리다" },
      { "en": "sympathy", "ko": "동정, 공감" },
      { "en": "sympathize", "ko": "동정하다, 공감하다" },
      { "en": "empathy", "ko": "감정이입, 공감" },
      { "en": "compassion", "ko": "연민, 동정심" },
      { "en": "pity", "ko": "동정, 불쌍히 여김, 유감" },
      { "en": "mercy", "ko": "자비, 연민" },
      { "en": "merciful", "ko": "자비로운" },
      { "en": "ruthless", "ko": "무자비한, 가차없는" },
      { "en": "cruel", "ko": "잔인한, 잔혹한" },
      { "en": "cruelty", "ko": "잔인함" },
      { "en": "hostile", "ko": "적대적인" },
      { "en": "hostility", "ko": "적대감" },
      { "en": "aggressive", "ko": "공격적인, 적극적인" },
      { "en": "aggression", "ko": "공격, 침략" },
      { "en": "violent", "ko": "폭력적인, 격렬한" },
      { "en": "violence", "ko": "폭력, 폭력 행위" },
      { "en": "gentle", "ko": "온화한, 부드러운" },
      { "en": "mild", "ko": "온화한, 순한" },
      { "en": "tender", "ko": "부드러운, 다정한" },
      { "en": "generous", "ko": "관대한, 후한" },
      { "en": "generosity", "ko": "관대함, 아량" },
      { "en": "selfish", "ko": "이기적인" },
      { "en": "selfless", "ko": "이타적인, 사심 없는" },
      { "en": "altruistic", "ko": "이타적인" },
      { "en": "greedy", "ko": "탐욕스러운, 욕심 많은" },
      { "en": "greed", "ko": "탐욕, 욕심" },
      { "en": "modest", "ko": "겸손한, 알맞은" },
      { "en": "modesty", "ko": "겸손" },
      { "en": "humble", "ko": "겸손한, 초라한" },
      { "en": "arrogant", "ko": "거만한, 오만한" },
      { "en": "arrogance", "ko": "오만, 거만" }
    ]
  },
  {
    "id": "wm2000_day_13",
    "book": "워드마스터 수능 2000",
    "title": "Day 13",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "communicate", "ko": "의사소통하다, 전달하다" },
      { "en": "communication", "ko": "의사소통, 통신" },
      { "en": "express", "ko": "표현하다, 급행의" },
      { "en": "expression", "ko": "표현, 표정" },
      { "en": "expressive", "ko": "표현이 풍부한" },
      { "en": "convey", "ko": "전달하다, 운르다" },
      { "en": "deliver", "ko": "전달하다, 배달하다, 연설하다" },
      { "en": "delivery", "ko": "배달, 전달" },
      { "en": "message", "ko": "메시지, 전갈" },
      { "en": "messenger", "ko": "전령, 배달원" },
      { "en": "signal", "ko": "신호, 신호를 보내다" },
      { "en": "gesture", "ko": "몸짓, 제스처" },
      { "en": "sign", "ko": "표지판, 서명하다, 징후" },
      { "en": "symbol", "ko": "상징, 기호" },
      { "en": "symbolize", "ko": "상징하다" },
      { "en": "metaphor", "ko": "은유, 비유" },
      { "en": "analogy", "ko": "비유, 유사점" },
      { "en": "dialogue", "ko": "대화, 문답" },
      { "en": "conversation", "ko": "대화, 담화" },
      { "en": "chat", "ko": "잡담하다, 대화" },
      { "en": "discuss", "ko": "토론하다, 논의하다" },
      { "en": "discussion", "ko": "토론, 논의" },
      { "en": "debate", "ko": "토론, 논쟁하다" },
      { "en": "argue", "ko": "주장하다, 언쟁하다" },
      { "en": "argument", "ko": "주장, 논쟁" },
      { "en": "persuade", "ko": "설득하다" },
      { "en": "persuasion", "ko": "설득" },
      { "en": "persuasive", "ko": "설득력 있는" },
      { "en": "convince", "ko": "확신시키다, 납득시키다" },
      { "en": "convincing", "ko": "설득력 있는" },
      { "en": "broadcast", "ko": "방송하다, 방영" },
      { "en": "network", "ko": "네트워크, 망" },
      { "en": "journal", "ko": "일기, 학술지, 잡지" },
      { "en": "journalism", "ko": "언론, 저널리즘" },
      { "en": "journalist", "ko": "기자, 저널리스트" },
      { "en": "headline", "ko": "표제, 헤드라인" },
      { "en": "article", "ko": "기사, 조항, 물건" },
      { "en": "column", "ko": "기둥, 칼럼, 난" },
      { "en": "editorial", "ko": "사설, 편집의" },
      { "en": "press", "ko": "언론, 누르다, 인쇄기" }
    ]
  },
  {
    "id": "wm2000_day_14",
    "book": "워드마스터 수능 2000",
    "title": "Day 14",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "geography", "ko": "지리학, 지리" },
      { "en": "geographic", "ko": "지리적인" },
      { "en": "region", "ko": "지역, 지방" },
      { "en": "regional", "ko": "지역의, 지방의" },
      { "en": "district", "ko": "구역, 지역" },
      { "en": "area", "ko": "면적, 지역, 영역" },
      { "en": "zone", "ko": "구역, 지대" },
      { "en": "territory", "ko": "영토, 영역" },
      { "en": "boundary", "ko": "경계, 한계" },
      { "en": "border", "ko": "국경, 가장자리" },
      { "en": "frontier", "ko": "국경, 미개척 영역" },
      { "en": "location", "ko": "위치, 장소" },
      { "en": "locate", "ko": "위치시키다, 찾아내다" },
      { "en": "destination", "ko": "목적지, 행선지" },
      { "en": "route", "ko": "경로, 노선" },
      { "en": "path", "ko": "길, 경로" },
      { "en": "passage", "ko": "통로, 통과, 구절" },
      { "en": "travel", "ko": "여행하다, 이동하다" },
      { "en": "journey", "ko": "여행, 여정" },
      { "en": "trip", "ko": "여행, 발을 헛디디다" },
      { "en": "tour", "ko": "관광, 여행하다" },
      { "en": "tourism", "ko": "관광업" },
      { "en": "tourist", "ko": "관광객" },
      { "en": "voyage", "ko": "항해, 여행" },
      { "en": "cruise", "ko": "유람선 여행" },
      { "en": "flight", "ko": "비행, 항공편" },
      { "en": "departure", "ko": "출발" },
      { "en": "depart", "ko": "출발하다, 떠나다" },
      { "en": "arrival", "ko": "도착" },
      { "en": "arrive", "ko": "도착하다" },
      { "en": "transport", "ko": "수송하다, 운송" },
      { "en": "transportation", "ko": "교통수단, 수송" },
      { "en": "vehicle", "ko": "차량, 탈것, 수단" },
      { "en": "passenger", "ko": "승객" },
      { "en": "commute", "ko": "통근하다, 통근" },
      { "en": "pedestrian", "ko": "보행자" },
      { "en": "traffic", "ko": "교통, 교통량" },
      { "en": "congestion", "ko": "혼잡, 정체" },
      { "en": "highway", "ko": "고속도로" },
      { "en": "transit", "ko": "환승, 수송" }
    ]
  },
  {
    "id": "wm2000_day_15",
    "book": "워드마스터 수능 2000",
    "title": "Day 15",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "universe", "ko": "우주, 만물" },
      { "en": "universal", "ko": "보편적인, 우주의" },
      { "en": "galaxy", "ko": "은하, 은하수" },
      { "en": "solar", "ko": "태양의" },
      { "en": "lunar", "ko": "달의" },
      { "en": "planet", "ko": "행성" },
      { "en": "planetary", "ko": "행성의" },
      { "en": "satellite", "ko": "위성, 인공위성" },
      { "en": "orbit", "ko": "궤도, 궤도를 돌다" },
      { "en": "gravity", "ko": "중력, 중대성" },
      { "en": "gravitational", "ko": "중력의" },
      { "en": "atmosphere", "ko": "대기, 공기, 분위기" },
      { "en": "atmospheric", "ko": "대기의" },
      { "en": "radiation", "ko": "방사선, 복사" },
      { "en": "radiate", "ko": "방사하다, 내뿜다" },
      { "en": "spectrum", "ko": "스펙트럼, 범위" },
      { "en": "telescope", "ko": "망원경" },
      { "en": "microscope", "ko": "현미경" },
      { "en": "spacecraft", "ko": "우주선" },
      { "en": "astronaut", "ko": "우주비행사" },
      { "en": "astronomy", "ko": "천문학" },
      { "en": "astronomer", "ko": "천문학자" },
      { "en": "astrology", "ko": "점성술" },
      { "en": "physics", "ko": "물리학" },
      { "en": "physicist", "ko": "물리학자" },
      { "en": "motion", "ko": "운동, 움직임, 발의" },
      { "en": "velocity", "ko": "속도" },
      { "en": "acceleration", "ko": "가속도" },
      { "en": "accelerate", "ko": "가속하다, 촉진하다" },
      { "en": "mass", "ko": "질량, 덩어리, 대중" },
      { "en": "density", "ko": "밀도, 농도" },
      { "en": "dense", "ko": "빽빽한, 밀집한" },
      { "en": "friction", "ko": "마찰, 마찰력, 갈등" },
      { "en": "magnet", "ko": "자석, 끌어당기는 것" },
      { "en": "magnetic", "ko": "자석의, 매력 있는" },
      { "en": "particle", "ko": "입자, 극소량" },
      { "en": "atom", "ko": "원자" },
      { "en": "atomic", "ko": "원자의" },
      { "en": "molecule", "ko": "분자" },
      { "en": "molecular", "ko": "분자의" }
    ]
  },
  {
    "id": "wm2000_day_16",
    "book": "워드마스터 수능 2000",
    "title": "Day 16",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "biology", "ko": "생물학" },
      { "en": "biological", "ko": "생물학적인" },
      { "en": "organism", "ko": "유기체, 생물" },
      { "en": "cell", "ko": "세포, 칸" },
      { "en": "cellular", "ko": "세포의" },
      { "en": "gene", "ko": "유전자" },
      { "en": "genetic", "ko": "유전의, 유전학의" },
      { "en": "genetics", "ko": "유전학" },
      { "en": "genome", "ko": "게놈, 유전체" },
      { "en": "DNA", "ko": "디엔에이, 유전자 본체" },
      { "en": "heredity", "ko": "유전" },
      { "en": "hereditary", "ko": "유전적인" },
      { "en": "inherit", "ko": "물려받다, 상속하다" },
      { "en": "inheritance", "ko": "유산, 상속" },
      { "en": "evolve", "ko": "진화하다, 발전하다" },
      { "en": "evolution", "ko": "진화, 발전" },
      { "en": "evolutionary", "ko": "진화의" },
      { "en": "adapt", "ko": "적응하다, 맞추다" },
      { "en": "adaptation", "ko": "적응, 각색" },
      { "en": "survival", "ko": "생존" },
      { "en": "survive", "ko": "살아남다, 생존하다" },
      { "en": "survivor", "ko": "생존자" },
      { "en": "mutation", "ko": "돌연변이" },
      { "en": "mutate", "ko": "돌연변이를 일으키다" },
      { "en": "reproduce", "ko": "번식하다, 복제하다" },
      { "en": "reproduction", "ko": "번식, 생식, 복제" },
      { "en": "offspring", "ko": "자손, 새끼" },
      { "en": "ancestor", "ko": "조상, 선조" },
      { "en": "descendant", "ko": "자손, 후손" },
      { "en": "trait", "ko": "형질, 특성" },
      { "en": "tissue", "ko": "조직, 화장지" },
      { "en": "organ", "ko": "장기, 기관, 오르간" },
      { "en": "system", "ko": "체계, 계통, 계" },
      { "en": "skeleton", "ko": "골격, 뼈대" },
      { "en": "bone", "ko": "뼈" },
      { "en": "muscle", "ko": "근육" },
      { "en": "muscular", "ko": "근육의, 강건한" },
      { "en": "nerve", "ko": "신경, 용기" },
      { "en": "nervous", "ko": "신경의, 긴장한" },
      { "en": "brain", "ko": "뇌, 두뇌, 지능" }
    ]
  },
  {
    "id": "wm2000_day_17",
    "book": "워드마스터 수능 2000",
    "title": "Day 17",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "nutrition", "ko": "영양, 영양 섭취" },
      { "en": "nutrient", "ko": "영양소, 영양분" },
      { "en": "nutritious", "ko": "영양가 있는" },
      { "en": "diet", "ko": "식습관, 다이어트, 식단" },
      { "en": "dietary", "ko": "음식의, 식이의" },
      { "en": "calorie", "ko": "칼로리, 열량" },
      { "en": "protein", "ko": "단백질" },
      { "en": "carbohydrate", "ko": "탄수화물" },
      { "en": "fat", "ko": "지방, 살찐" },
      { "en": "vitamin", "ko": "비타민" },
      { "en": "mineral", "ko": "미네랄, 광물" },
      { "en": "fiber", "ko": "섬유질, 섬유" },
      { "en": "ingredient", "ko": "재료, 성분" },
      { "en": "recipe", "ko": "조리법, 비결" },
      { "en": "flavor", "ko": "맛, 풍미" },
      { "en": "digest", "ko": "소화하다, 요약하다" },
      { "en": "digestion", "ko": "소화, 소화력" },
      { "en": "digestive", "ko": "소화의" },
      { "en": "appetite", "ko": "식욕, 욕구" },
      { "en": "hunger", "ko": "굶주림, 배고픔" },
      { "en": "thirsty", "ko": "목마른" },
      { "en": "hygiene", "ko": "위생, 청결" },
      { "en": "sanitary", "ko": "위생의, 위생적인" },
      { "en": "disease", "ko": "질병, 질환" },
      { "en": "illness", "ko": "질병, 아픔" },
      { "en": "symptom", "ko": "증상, 징후" },
      { "en": "syndrome", "ko": "증후군" },
      { "en": "fever", "ko": "열, 발열" },
      { "en": "infection", "ko": "감염, 전염" },
      { "en": "infect", "ko": "감염시키다" },
      { "en": "infectious", "ko": "전염성의" },
      { "en": "contagious", "ko": "전염성의, 전파되는" },
      { "en": "epidemic", "ko": "유행병, 유행성의" },
      { "en": "pandemic", "ko": "전국적 유행병" },
      { "en": "immune", "ko": "면역의, 면제된" },
      { "en": "immunity", "ko": "면역, 면제" },
      { "en": "vaccine", "ko": "백신" },
      { "en": "vaccinate", "ko": "예방접종을 하다" },
      { "en": "diagnose", "ko": "진단하다" },
      { "en": "diagnosis", "ko": "진단" }
    ]
  },
  {
    "id": "wm2000_day_18",
    "book": "워드마스터 수능 2000",
    "title": "Day 18",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "architecture", "ko": "건축, 건축학" },
      { "en": "architect", "ko": "건축가, 설계자" },
      { "en": "architectural", "ko": "건축의" },
      { "en": "structure", "ko": "구조, 구조물" },
      { "en": "structural", "ko": "구조의" },
      { "en": "construct", "ko": "건설하다, 구성하다" },
      { "en": "construction", "ko": "건설, 공사" },
      { "en": "destructive", "ko": "파괴적인" },
      { "en": "destroy", "ko": "파괴하다" },
      { "en": "infrastructure", "ko": "사회 기반 시설" },
      { "en": "facility", "ko": "시설, 편의시설, 재능" },
      { "en": "foundation", "ko": "기초, 토대, 재단" },
      { "en": "framework", "ko": "틀, 뼈대" },
      { "en": "pillar", "ko": "기둥, 중심축" },
      { "en": "column", "ko": "원주, 기둥" },
      { "en": "ceiling", "ko": "천장, 상한선" },
      { "en": "floor", "ko": "바닥, 층" },
      { "en": "roof", "ko": "지붕" },
      { "en": "shelter", "ko": "주거지, 피난처, 보호하다" },
      { "en": "dwelling", "ko": "주거, 서식지" },
      { "en": "residence", "ko": "거주지, 주택" },
      { "en": "resident", "ko": "주민, 거주자" },
      { "en": "residential", "ko": "주거의" },
      { "en": "reside", "ko": "살다, 거주하다" },
      { "en": "inhabit", "ko": "살다, 서식하다" },
      { "en": "inhabitant", "ko": "주민, 서식 동물" },
      { "en": "urban", "ko": "도시의" },
      { "en": "rural", "ko": "시골의, 농촌의" },
      { "en": "suburb", "ko": "교외, 근교" },
      { "en": "suburban", "ko": "교외의" },
      { "en": "metropolis", "ko": "대도시, 중심지" },
      { "en": "metropolitan", "ko": "대도시의" },
      { "en": "downtown", "ko": "도심, 시내" },
      { "en": "skyscraper", "ko": "초고층 건물" },
      { "en": "estate", "ko": "부동산, 사유지" },
      { "en": "property", "ko": "재산, 부동산, 속성" },
      { "en": "tenant", "ko": "세입자, 임차인" },
      { "en": "landlord", "ko": "임대인, 집주인" },
      { "en": "rent", "ko": "임대료, 빌리다" },
      { "en": "mortgage", "ko": "주택 담보 대출" }
    ]
  },
  {
    "id": "wm2000_day_19",
    "book": "워드마스터 수능 2000",
    "title": "Day 19",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "sense", "ko": "감각, 의미, 분별력" },
      { "en": "sensory", "ko": "감각의" },
      { "en": "sensible", "ko": "현명한, 분별 있는" },
      { "en": "sensitive", "ko": "민감한, 예민한" },
      { "en": "sensitivity", "ko": "민감성, 감수성" },
      { "en": "perceive", "ko": "지각하다, 인지하다" },
      { "en": "perception", "ko": "지각, 인식" },
      { "en": "perceptive", "ko": "통찰력 있는" },
      { "en": "sight", "ko": "시각, 시력, 광경" },
      { "en": "vision", "ko": "시력, 시야, 비전" },
      { "en": "visual", "ko": "시각의, 눈에 보이는" },
      { "en": "visualize", "ko": "시각화하다, 상상하다" },
      { "en": "hearing", "ko": "청각, 청력, 공청회" },
      { "en": "auditory", "ko": "청각의" },
      { "en": "audible", "ko": "들리는, 들을 수 있는" },
      { "en": "taste", "ko": "미각, 맛, 취향" },
      { "en": "flavor", "ko": "맛, 향미" },
      { "en": "smell", "ko": "후각, 냄새, 맡다" },
      { "en": "odor", "ko": "냄새, 악취" },
      { "en": "scent", "ko": "향기, 냄새" },
      { "en": "touch", "ko": "촉각, 만지다" },
      { "en": "tactile", "ko": "촉각의" },
      { "en": "cognition", "ko": "인지, 인식" },
      { "en": "cognitive", "ko": "인지의, 인식의" },
      { "en": "comprehend", "ko": "이해하다, 파악하다" },
      { "en": "comprehension", "ko": "이해, 이해력" },
      { "en": "comprehensive", "ko": "포괄적인, 종합적인" },
      { "en": "recognize", "ko": "알아보다, 인정하다" },
      { "en": "recognition", "ko": "인식, 인정" },
      { "en": "aware", "ko": "알고 있는" },
      { "en": "awareness", "ko": "인식, 자각" },
      { "en": "conscious", "ko": "의식하는, 자각하는" },
      { "en": "consciousness", "ko": "의식, 자각" },
      { "en": "unconscious", "ko": "무의식의, 의식을 잃은" },
      { "en": "subconscious", "ko": "잠재의식의" },
      { "en": "intuition", "ko": "직관, 직감" },
      { "en": "intuitive", "ko": "직관적인" },
      { "en": "insight", "ko": "통찰력, 안목" },
      { "en": "logic", "ko": "논리, 논리학" },
      { "en": "reasoning", "ko": "추론, 추리" }
    ]
  },
  {
    "id": "wm2000_day_20",
    "book": "워드마스터 수능 2000",
    "title": "Day 20",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "cooperate", "ko": "협력하다, 협동하다" },
      { "en": "cooperation", "ko": "협력, 협동" },
      { "en": "cooperative", "ko": "협력적인, 협동조합" },
      { "en": "collaborate", "ko": "공동 작업하다, 협력하다" },
      { "en": "collaboration", "ko": "협업, 합작" },
      { "en": "collaborative", "ko": "협력적인" },
      { "en": "coordinate", "ko": "조정하다, 조화시키다" },
      { "en": "coordination", "ko": "조정, 조화" },
      { "en": "ally", "ko": "동맹국, 동맹자" },
      { "en": "alliance", "ko": "동맹, 연합" },
      { "en": "partner", "ko": "동반자, 협력자" },
      { "en": "partnership", "ko": "동반자 관계" },
      { "en": "colleague", "ko": "동료" },
      { "en": "peer", "ko": "동료, 또래, 응시하다" },
      { "en": "companion", "ko": "동반자, 친구" },
      { "en": "comrade", "ko": "동지, 전우" },
      { "en": "conflict", "ko": "갈등, 충돌, 대립하다" },
      { "en": "confront", "ko": "직면하다, 맞서다" },
      { "en": "confrontation", "ko": "대립, 대치" },
      { "en": "dispute", "ko": "분쟁, 논쟁하다" },
      { "en": "quarrel", "ko": "말다툼, 다투다" },
      { "en": "friction", "ko": "마찰, 불화" },
      { "en": "hostility", "ko": "적대감, 적개심" },
      { "en": "rival", "ko": "경쟁자, 필적하다" },
      { "en": "rivalry", "ko": "경쟁, 대항" },
      { "en": "compromise", "ko": "타협하다, 타협, 손상시키다" },
      { "en": "negotiate", "ko": "협상하다, 절충하다" },
      { "en": "negotiation", "ko": "협상, 교섭" },
      { "en": "reconcile", "ko": "화해시키다, 조화시키다" },
      { "en": "reconciliation", "ko": "화해, 조화" },
      { "en": "mediate", "ko": "중재하다, 조정하다" },
      { "en": "mediation", "ko": "중재, 조정" },
      { "en": "mediator", "ko": "중재자" },
      { "en": "harmony", "ko": "조화, 화합" },
      { "en": "harmonious", "ko": "조화로운" },
      { "en": "solidarity", "ko": "연대, 결속" },
      { "en": "unite", "ko": "결합하다, 단결하다" },
      { "en": "unity", "ko": "통일성, 단결" },
      { "en": "isolate", "ko": "격리하다, 고립시키다" },
      { "en": "isolation", "ko": "고립, 격리" }
    ]
  },
  {
    "id": "wm2000_day_21",
    "book": "워드마스터 수능 2000",
    "title": "Day 21",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "desire", "ko": "욕구, 갈망, 바라다" },
      { "en": "aspire", "ko": "열망하다, 염원하다" },
      { "en": "aspiration", "ko": "열망, 포부" },
      { "en": "ambition", "ko": "야망, 야심" },
      { "en": "ambitious", "ko": "야심 찬, 의욕적인" },
      { "en": "motive", "ko": "동기, 동인" },
      { "en": "motivate", "ko": "동기를 부여하다" },
      { "en": "motivation", "ko": "동기 부여" },
      { "en": "incentive", "ko": "유인책, 장려금" },
      { "en": "urge", "ko": "촉구하다, 강한 충동" },
      { "en": "impulse", "ko": "충동, 자극" },
      { "en": "impulsive", "ko": "충동적인" },
      { "en": "craving", "ko": "갈망, 열망" },
      { "en": "greed", "ko": "탐욕, 식탐" },
      { "en": "passion", "ko": "열정, 격정" },
      { "en": "passionate", "ko": "열정적인" },
      { "en": "enthusiasm", "ko": "열정, 열광" },
      { "en": "enthusiastic", "ko": "열렬한, 열정적인" },
      { "en": "zeal", "ko": "열의, 열성" },
      { "en": "eager", "ko": "간절히 바라는, 열심인" },
      { "en": "intent", "ko": "의도, 전념하는" },
      { "en": "intention", "ko": "의도, 의향" },
      { "en": "intentional", "ko": "의도적인, 고의의" },
      { "en": "purpose", "ko": "목적, 취지" },
      { "en": "purposeful", "ko": "목적이 있는, 단호한" },
      { "en": "objective", "ko": "목표, 객관적인" },
      { "en": "aim", "ko": "겨냥하다, 목표" },
      { "en": "goal", "ko": "목표, 골" },
      { "en": "target", "ko": "목표, 표적" },
      { "en": "ideal", "ko": "이상적인, 이상" },
      { "en": "optimistic", "ko": "낙관적인, 긍정적인" },
      { "en": "optimism", "ko": "낙관주의" },
      { "en": "pessimistic", "ko": "비관적인" },
      { "en": "pessimism", "ko": "비관주의" },
      { "en": "cynical", "ko": "냉소적인, 부정적인" },
      { "en": "skeptical", "ko": "회의적인, 의심 많은" },
      { "en": "doubtful", "ko": "의심스러운" },
      { "en": "hesitant", "ko": "망설이는, 주저하는" },
      { "en": "reluctant", "ko": "꺼리는, 주저하는" },
      { "en": "willing", "ko": "기꺼이 하는, 자진해서 하는" }
    ]
  },
  {
    "id": "wm2000_day_22",
    "book": "워드마스터 수능 2000",
    "title": "Day 22",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "corporation", "ko": "기업, 법인" },
      { "en": "corporate", "ko": "기업의, 법인의" },
      { "en": "enterprise", "ko": "기업, 사업, 진취성" },
      { "en": "executive", "ko": "경영진, 임원, 실행의" },
      { "en": "manager", "ko": "관리자, 경영자" },
      { "en": "supervisor", "ko": "감독관, 관리자" },
      { "en": "supervise", "ko": "감독하다, 지휘하다" },
      { "en": "recruit", "ko": "채용하다, 신입사원" },
      { "en": "recruitment", "ko": "채용, 신병 모집" },
      { "en": "hire", "ko": "고용하다" },
      { "en": "dismiss", "ko": "해고하다, 묵살하다" },
      { "en": "layoff", "ko": "일시 해고, 정리해고" },
      { "en": "resign", "ko": "사임하다, 사직하다" },
      { "en": "resignation", "ko": "사직, 사임" },
      { "en": "retire", "ko": "은퇴하다, 퇴직하다" },
      { "en": "retirement", "ko": "은퇴, 퇴직" },
      { "en": "pension", "ko": "연금" },
      { "en": "salary", "ko": "급여, 월급" },
      { "en": "wage", "ko": "임금, 주급" },
      { "en": "bonus", "ko": "보너스, 상여금" },
      { "en": "compensation", "ko": "보상, 배상, 급여" },
      { "en": "compensate", "ko": "보상하다, 보충하다" },
      { "en": "workplace", "ko": "직장, 근무지" },
      { "en": "colleague", "ko": "동료" },
      { "en": "profession", "ko": "전문직, 직업" },
      { "en": "professional", "ko": "전문적인, 전문가" },
      { "en": "vocation", "ko": "천직, 소명, 직업" },
      { "en": "occupy", "ko": "차지하다, 점령하다" },
      { "en": "occupation", "ko": "직업, 점령" },
      { "en": "occupational", "ko": "직업의, 업무상의" },
      { "en": "career", "ko": "경력, 직업 경로" },
      { "en": "promotion", "ko": "승진, 홍보, 촉진" },
      { "en": "promote", "ko": "승진시키다, 촉진하다" },
      { "en": "demote", "ko": "강등시키다" },
      { "en": "workload", "ko": "업무량" },
      { "en": "overtime", "ko": "초과 근무, 잔업" },
      { "en": "shift", "ko": "근무 교대, 교대조, 변화" },
      { "en": "productivity", "ko": "생산성" },
      { "en": "efficiency", "ko": "효율성, 능률" },
      { "en": "efficient", "ko": "효율적인, 유능한" }
    ]
  },
  {
    "id": "wm2000_day_23",
    "book": "워드마스터 수능 2000",
    "title": "Day 23",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "contract", "ko": "계약, 계약서, 수축하다" },
      { "en": "contractor", "ko": "계약자, 시공업자" },
      { "en": "clause", "ko": "조항, 절" },
      { "en": "obligation", "ko": "의무, 책임" },
      { "en": "obligatory", "ko": "의무적인, 필수의" },
      { "en": "duty", "ko": "의무, 직무, 관세" },
      { "en": "responsible", "ko": "책임이 있는" },
      { "en": "responsibility", "ko": "책임, 의무" },
      { "en": "liable", "ko": "책임이 있는, ~하기 쉬운" },
      { "en": "liability", "ko": "법적 책임, 부채" },
      { "en": "right", "ko": "권리, 옳은, 오른쪽" },
      { "en": "privilege", "ko": "특권, 특혜" },
      { "en": "entitle", "ko": "자격을 주다, 제목을 붙이다" },
      { "en": "authorize", "ko": "권한을 부여하다, 허가하다" },
      { "en": "authority", "ko": "권위, 권한, 당국" },
      { "en": "comply", "ko": "따르다, 준수하다" },
      { "en": "compliance", "ko": "준수, 순응" },
      { "en": "conform", "ko": "따르다, 일치하다" },
      { "en": "obey", "ko": "복종하다, 따르다" },
      { "en": "obedient", "ko": "순종하는, 복종하는" },
      { "en": "violate", "ko": "위반하다, 침해하다" },
      { "en": "violation", "ko": "위반, 침해" },
      { "en": "breach", "ko": "위반, 파기, 깨뜨리다" },
      { "en": "infringe", "ko": "침해하다, 어기다" },
      { "en": "infringement", "ko": "침해, 위반" },
      { "en": "lawsuit", "ko": "소송" },
      { "en": "sue", "ko": "고소하다, 소송을 제기하다" },
      { "en": "plaintiff", "ko": "원고 (소송 제기자)" },
      { "en": "defendant", "ko": "피고" },
      { "en": "attorney", "ko": "변호사, 대리인" },
      { "en": "lawyer", "ko": "변호사" },
      { "en": "counsel", "ko": "조언, 변호인, 상담하다" },
      { "en": "verdict", "ko": "평결, 판단" },
      { "en": "sentence", "ko": "선고하다, 문장, 형벌" },
      { "en": "guilty", "ko": "유죄의, 죄책감이 드는" },
      { "en": "innocent", "ko": "무죄의, 순진한" },
      { "en": "innocence", "ko": "무죄, 결백, 순진" },
      { "en": "witness", "ko": "목격자, 증인, 목격하다" },
      { "en": "testimony", "ko": "증언, 증거" },
      { "en": "evidence", "ko": "증거, 흔적" }
    ]
  },
  {
    "id": "wm2000_day_24",
    "book": "워드마스터 수능 2000",
    "title": "Day 24",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "military", "ko": "군사의, 군대" },
      { "en": "soldier", "ko": "군인, 병사" },
      { "en": "troop", "ko": "군대, 무리" },
      { "en": "army", "ko": "육군, 군대" },
      { "en": "navy", "ko": "해군" },
      { "en": "airforce", "ko": "공군" },
      { "en": "weapon", "ko": "무기, 흉기" },
      { "en": "arms", "ko": "무기, 군비, 품" },
      { "en": "armor", "ko": "갑옷, 장갑" },
      { "en": "shield", "ko": "방패, 보호하다" },
      { "en": "sword", "ko": "칼, 검" },
      { "en": "missile", "ko": "미사일" },
      { "en": "bomb", "ko": "폭탄, 폭파하다" },
      { "en": "explosive", "ko": "폭발성의, 폭발물" },
      { "en": "explode", "ko": "폭발하다" },
      { "en": "explosion", "ko": "폭발, 파열" },
      { "en": "blast", "ko": "폭발, 돌풍, 폭파하다" },
      { "en": "casualty", "ko": "사상자, 피해자" },
      { "en": "refugee", "ko": "난민, 망명자" },
      { "en": "shelter", "ko": "피난처, 대피소" },
      { "en": "invade", "ko": "침략하다, 침입하다" },
      { "en": "invasion", "ko": "침략, 침입" },
      { "en": "invader", "ko": "침략자" },
      { "en": "conquer", "ko": "정복하다, 탈환하다" },
      { "en": "conquest", "ko": "정복, 점령" },
      { "en": "occupy", "ko": "점령하다, 점유하다" },
      { "en": "truce", "ko": "휴전, 정전" },
      { "en": "ceasefire", "ko": "휴전, 사격 중지" },
      { "en": "treaty", "ko": "조약, 협정" },
      { "en": "pact", "ko": "약정, 협정" },
      { "en": "peace", "ko": "평화, 평온" },
      { "en": "peaceful", "ko": "평화로운" },
      { "en": "security", "ko": "안보, 보안, 보증" },
      { "en": "threat", "ko": "위협, 협박" },
      { "en": "threaten", "ko": "위협하다, 협박하다" },
      { "en": "terror", "ko": "공포, 테러" },
      { "en": "terrorism", "ko": "테러리즘" },
      { "en": "terrorist", "ko": "테러리스트" },
      { "en": "disarmament", "ko": "군축, 군비 축소" },
      { "en": "surrender", "ko": "항복하다, 인도하다" }
    ]
  },
  {
    "id": "wm2000_day_25",
    "book": "워드마스터 수능 2000",
    "title": "Day 25",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "philosophy", "ko": "철학" },
      { "en": "philosopher", "ko": "철학자" },
      { "en": "philosophical", "ko": "철학적인" },
      { "en": "ethics", "ko": "윤리학, 도덕" },
      { "en": "ethical", "ko": "윤리적인, 도덕적인" },
      { "en": "moral", "ko": "도덕적인, 교훈" },
      { "en": "morality", "ko": "도덕, 도덕성" },
      { "en": "immoral", "ko": "부도덕한" },
      { "en": "virtue", "ko": "미덕, 덕목, 장점" },
      { "en": "virtuous", "ko": "도덕적인, 덕이 높은" },
      { "en": "vice", "ko": "악덕, 결함, 부(副)" },
      { "en": "sin", "ko": "죄, 죄악" },
      { "en": "sacred", "ko": "신성한, 성스러운" },
      { "en": "holy", "ko": "거룩한, 성스러운" },
      { "en": "divine", "ko": "신의, 신성한" },
      { "en": "religion", "ko": "종교" },
      { "en": "religious", "ko": "종교적인, 신앙심 깊은" },
      { "en": "faith", "ko": "믿음, 신앙" },
      { "en": "faithful", "ko": "충실한, 신의 있는" },
      { "en": "belief", "ko": "신념, 확신" },
      { "en": "doctrine", "ko": "교리, 신조" },
      { "en": "dogma", "ko": "교조, 독단적 신조" },
      { "en": "pray", "ko": "기도하다, 빌다" },
      { "en": "prayer", "ko": "기도, 기도문" },
      { "en": "worship", "ko": "예배, 숭배하다" },
      { "en": "idol", "ko": "우상, 아이돌" },
      { "en": "temple", "ko": "사원, 신전, 관자놀이" },
      { "en": "church", "ko": "교회" },
      { "en": "cathedral", "ko": "대성당" },
      { "en": "priest", "ko": "사제, 성직자" },
      { "en": "monk", "ko": "수도승, 승려" },
      { "en": "meditation", "ko": "명상, 묵상" },
      { "en": "meditate", "ko": "명상하다" },
      { "en": "spiritual", "ko": "영적인, 정신적인" },
      { "en": "soul", "ko": "영혼, 혼" },
      { "en": "spirit", "ko": "정신, 영혼, 기백" },
      { "en": "conscience", "ko": "양심" },
      { "en": "righteous", "ko": "의로운, 당연한" },
      { "en": "noble", "ko": "고결한, 귀족의" },
      { "en": "destiny", "ko": "운명, 숙명" }
    ]
  },
  {
    "id": "wm2000_day_26",
    "book": "워드마스터 수능 2000",
    "title": "Day 26",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "industry", "ko": "산업, 공업, 근면" },
      { "en": "industrial", "ko": "산업의, 공업의" },
      { "en": "industrialize", "ko": "산업화하다" },
      { "en": "manufacture", "ko": "제조하다, 생산하다" },
      { "en": "manufacturer", "ko": "제조업자, 제조사" },
      { "en": "factory", "ko": "공장" },
      { "en": "plant", "ko": "공장, 식물, 심다" },
      { "en": "facility", "ko": "설비, 시설" },
      { "en": "machinery", "ko": "기계류" },
      { "en": "equipment", "ko": "장비, 설비" },
      { "en": "automate", "ko": "자동화하다" },
      { "en": "automation", "ko": "자동화" },
      { "en": "agriculture", "ko": "농업, 농경" },
      { "en": "agricultural", "ko": "농업의, 농사의" },
      { "en": "cultivate", "ko": "경작하다, 재배하다" },
      { "en": "cultivation", "ko": "경작, 재배" },
      { "en": "harvest", "ko": "수확하다, 수확기" },
      { "en": "crop", "ko": "농작물, 수확물" },
      { "en": "yield", "ko": "수확량, 산출하다" },
      { "en": "fertile", "ko": "비옥한, 번식력 있는" },
      { "en": "fertility", "ko": "비옥함, 출산율" },
      { "en": "fertilizer", "ko": "비료, 거름" },
      { "en": "barren", "ko": "척박한, 불모의" },
      { "en": "irrigation", "ko": "관개, 물을 대기" },
      { "en": "irrigate", "ko": "물을 대다, 관개하다" },
      { "en": "livestock", "ko": "가축" },
      { "en": "cattle", "ko": "소, 가축" },
      { "en": "pasture", "ko": "목초지, 방목장" },
      { "en": "energy", "ko": "에너지, 활력" },
      { "en": "energetic", "ko": "활동적인, 정력적인" },
      { "en": "fuel", "ko": "연료, 부채질하다" },
      { "en": "fossil", "ko": "화석" },
      { "en": "petroleum", "ko": "석유" },
      { "en": "coal", "ko": "석탄" },
      { "en": "electricity", "ko": "전기" },
      { "en": "electric", "ko": "전기의" },
      { "en": "generator", "ko": "발전기" },
      { "en": "nuclear", "ko": "원자력의, 핵의" },
      { "en": "solar", "ko": "태양열의, 태양의" },
      { "en": "turbine", "ko": "터빈" }
    ]
  },
  {
    "id": "wm2000_day_27",
    "book": "워드마스터 수능 2000",
    "title": "Day 27",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "duration", "ko": "지속 기간, 지속" },
      { "en": "temporary", "ko": "일시적인, 임시의" },
      { "en": "permanent", "ko": "영구적인, 불변의" },
      { "en": "eternal", "ko": "영원한, 끊임없는" },
      { "en": "perpetual", "ko": "끊임없는, 영속하는" },
      { "en": "transient", "ko": "일시적인, 순간적인" },
      { "en": "instant", "ko": "즉각적인, 순간" },
      { "en": "instantaneous", "ko": "순간적인, 즉시의" },
      { "en": "simultaneous", "ko": "동시의, 동시에 일어나는" },
      { "en": "contemporary", "ko": "동시대의, 현대의" },
      { "en": "chronological", "ko": "연대기순의" },
      { "en": "decade", "ko": "10년" },
      { "en": "century", "ko": "1세기, 100년" },
      { "en": "millennium", "ko": "천년, 천년기" },
      { "en": "era", "ko": "시대, 연대" },
      { "en": "epoch", "ko": "신시대, 획기적인 사건" },
      { "en": "dimension", "ko": "차원, 크기, 규모" },
      { "en": "spatial", "ko": "공간의, 공간적인" },
      { "en": "infinite", "ko": "무한한, 막대한" },
      { "en": "finite", "ko": "한정된, 유한한" },
      { "en": "interval", "ko": "간격, 휴식 시간" },
      { "en": "span", "ko": "기간, 폭, 걸치다" },
      { "en": "pace", "ko": "속도, 걸음걸이" },
      { "en": "swift", "ko": "신속한, 빠른" },
      { "en": "rapid", "ko": "빠른, 급속한" },
      { "en": "gradual", "ko": "점진적인, 서서히 일어나는" },
      { "en": "prompt", "ko": "즉각적인, 촉발하다" },
      { "en": "delay", "ko": "지연시키다, 미루다" },
      { "en": "postpone", "ko": "연기하다, 미루다" },
      { "en": "suspend", "ko": "중단하다, 매달다" },
      { "en": "resume", "ko": "재개하다, 다시 시작하다" },
      { "en": "transform", "ko": "변형시키다, 탈바꿈하다" },
      { "en": "transformation", "ko": "변화, 변신" },
      { "en": "alter", "ko": "바꾸다, 변경하다" },
      { "en": "alteration", "ko": "변화, 개조" },
      { "en": "modify", "ko": "수정하다, 조절하다" },
      { "en": "modification", "ko": "수정, 변경" },
      { "en": "shift", "ko": "이동하다, 변화" },
      { "en": "fluctuate", "ko": "변동하다, 오르내리다" },
      { "en": "fluctuation", "ko": "변동, 오르내림" }
    ]
  },
  {
    "id": "wm2000_day_28",
    "book": "워드마스터 수능 2000",
    "title": "Day 28",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "anxiety", "ko": "불안, 염려, 갈망" },
      { "en": "anxious", "ko": "불안한, 열망하는" },
      { "en": "panic", "ko": "공황, 극심한 공포" },
      { "en": "dread", "ko": "두려워하다, 공포" },
      { "en": "terror", "ko": "극심한 공포, 테러" },
      { "en": "horror", "ko": "공포, 전율" },
      { "en": "frighten", "ko": "겁주다, 놀라게 하다" },
      { "en": "scare", "ko": "겁주다, 두려움" },
      { "en": "delight", "ko": "기쁨, 즐겁게 하다" },
      { "en": "delighted", "ko": "아주 기뻐하는" },
      { "en": "ecstasy", "ko": "황홀경, 무아지경" },
      { "en": "joyful", "ko": "아주 기쁜" },
      { "en": "cheerful", "ko": "쾌활한, 발랄한" },
      { "en": "glad", "ko": "기쁜, 반가운" },
      { "en": "grief", "ko": "비탄, 큰 슬픔" },
      { "en": "grieve", "ko": "몹시 슬퍼하다" },
      { "en": "mourn", "ko": "애도하다, 슬퍼하다" },
      { "en": "sorrow", "ko": "슬픔, 비애" },
      { "en": "depression", "ko": "우울증, 불경기" },
      { "en": "depress", "ko": "우울하게 만들다" },
      { "en": "frustrate", "ko": "좌절시키다" },
      { "en": "frustration", "ko": "좌절, 불만" },
      { "en": "despair", "ko": "절망, 체념하다" },
      { "en": "hopeless", "ko": "절망적인, 가망 없는" },
      { "en": "rage", "ko": "분노, 격노" },
      { "en": "fury", "ko": "격분, 맹렬함" },
      { "en": "furious", "ko": "격노한, 맹렬한" },
      { "en": "irritate", "ko": "짜증나게 하다" },
      { "en": "irritation", "ko": "짜증, 염증" },
      { "en": "annoy", "ko": "짜증나게 하다" },
      { "en": "annoyance", "ko": "짜증, 골칫거리" },
      { "en": "resent", "ko": "분개하다, 억울하게 생각하다" },
      { "en": "resentment", "ko": "분개, 적의" },
      { "en": "jealous", "ko": "질투하는, 시기하는" },
      { "en": "jealousy", "ko": "질투, 시기" },
      { "en": "envy", "ko": "부러워하다, 질투" },
      { "en": "envious", "ko": "부러워하는" },
      { "en": "shame", "ko": "수치심, 부끄러움" },
      { "en": "embarrass", "ko": "당황하게 하다" },
      { "en": "embarrassment", "ko": "당황, 난처함" }
    ]
  },
  {
    "id": "wm2000_day_29",
    "book": "워드마스터 수능 2000",
    "title": "Day 29",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "information", "ko": "정보, 안내" },
      { "en": "informative", "ko": "유익한, 정보를 주는" },
      { "en": "inform", "ko": "알리다, 통지하다" },
      { "en": "software", "ko": "소프트웨어, 프로그램" },
      { "en": "hardware", "ko": "하드웨어, 장비" },
      { "en": "program", "ko": "프로그램, 계획" },
      { "en": "code", "ko": "암호, 부호, 규범, 코드" },
      { "en": "encode", "ko": "암호화하다, 부호화하다" },
      { "en": "decode", "ko": "해독하다" },
      { "en": "database", "ko": "데이터베이스" },
      { "en": "algorithm", "ko": "알고리즘, 연산 절차" },
      { "en": "cyber", "ko": "사이버의, 인터넷의" },
      { "en": "virtual", "ko": "가상의, 사실상의" },
      { "en": "virtually", "ko": "사실상, 가상으로" },
      { "en": "interface", "ko": "인터페이스, 접점" },
      { "en": "digital", "ko": "디지털의" },
      { "en": "analog", "ko": "아날로그의" },
      { "en": "network", "ko": "네트워크, 방송망" },
      { "en": "wireless", "ko": "무선의" },
      { "en": "telecommunication", "ko": "원거리 통신" },
      { "en": "access", "ko": "접근하다, 이용 권한" },
      { "en": "accessible", "ko": "접근하기 쉬운, 이용 가능한" },
      { "en": "storage", "ko": "저장, 보관소" },
      { "en": "store", "ko": "저장하다, 상점" },
      { "en": "retrieve", "ko": "되찾다, 검색하다" },
      { "en": "retrieval", "ko": "검색, 회수" },
      { "en": "transmit", "ko": "전송하다, 전달하다" },
      { "en": "transmission", "ko": "전송, 전파" },
      { "en": "server", "ko": "서버, 봉사자" },
      { "en": "client", "ko": "고객, 의뢰인" },
      { "en": "browser", "ko": "웹 브라우저" },
      { "en": "browse", "ko": "둘러보다, 검색하다" },
      { "en": "domain", "ko": "도메인, 영역, 분야" },
      { "en": "link", "ko": "연결하다, 링크" },
      { "en": "hyperlink", "ko": "하이퍼링크" },
      { "en": "security", "ko": "보안, 안전" },
      { "en": "encrypt", "ko": "암호화하다" },
      { "en": "privacy", "ko": "사생활, 사적 자유" },
      { "en": "platform", "ko": "플랫폼, 승강장" },
      { "en": "application", "ko": "응용프로그램, 적용, 신청" }
    ]
  },
  {
    "id": "wm2000_day_30",
    "book": "워드마스터 수능 2000",
    "title": "Day 30",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "geology", "ko": "지질학" },
      { "en": "geological", "ko": "지질학적인" },
      { "en": "geologist", "ko": "지질학자" },
      { "en": "crust", "ko": "지각, 껍질" },
      { "en": "mantle", "ko": "맨틀, 덮개" },
      { "en": "core", "ko": "핵, 중심부" },
      { "en": "plate", "ko": "판, 접시, 금속판" },
      { "en": "tectonics", "ko": "구조 지질학" },
      { "en": "earthquake", "ko": "지진" },
      { "en": "tremor", "ko": "미진, 떨림" },
      { "en": "fault", "ko": "단층, 잘못, 결함" },
      { "en": "volcano", "ko": "화산" },
      { "en": "volcanic", "ko": "화산의" },
      { "en": "eruption", "ko": "분출, 폭발" },
      { "en": "erupt", "ko": "분출하다, 터지다" },
      { "en": "magma", "ko": "마그마" },
      { "en": "lava", "ko": "용암" },
      { "en": "ash", "ko": "화산재, 재" },
      { "en": "meteorology", "ko": "기상학" },
      { "en": "meteorological", "ko": "기상학의" },
      { "en": "weather", "ko": "날씨, 기상" },
      { "en": "forecast", "ko": "예보, 예측하다" },
      { "en": "temperature", "ko": "온도, 기온" },
      { "en": "humidity", "ko": "습도" },
      { "en": "humid", "ko": "습한, 눅눅한" },
      { "en": "precipitation", "ko": "강수량, 침전" },
      { "en": "rainfall", "ko": "강우량" },
      { "en": "storm", "ko": "폭풍우" },
      { "en": "typhoon", "ko": "태풍" },
      { "en": "hurricane", "ko": "허리케인" },
      { "en": "tornado", "ko": "토네이도" },
      { "en": "blizzard", "ko": "눈보라" },
      { "en": "ocean", "ko": "대양, 바다" },
      { "en": "oceanic", "ko": "대양의, 해양의" },
      { "en": "marine", "ko": "해양의, 바다의" },
      { "en": "current", "ko": "해류, 기류, 전류" },
      { "en": "tide", "ko": "조수, 조석, 흐름" },
      { "en": "tidal", "ko": "조수의" },
      { "en": "coast", "ko": "해안, 연안" },
      { "en": "coastal", "ko": "해안의, 연안의" }
    ]
  },
  {
    "id": "wm2000_day_31",
    "book": "워드마스터 수능 2000",
    "title": "Day 31",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "infer", "ko": "추론하다, 암시하다" },
      { "en": "inference", "ko": "추론, 결론" },
      { "en": "deduce", "ko": "연역하다, 추론하다" },
      { "en": "deduction", "ko": "연역, 공제" },
      { "en": "induce", "ko": "귀납하다, 유도하다, 설득하다" },
      { "en": "induction", "ko": "귀납, 유도, 취임" },
      { "en": "premise", "ko": "전제, 부지" },
      { "en": "conclusion", "ko": "결론, 결말" },
      { "en": "conclude", "ko": "결론을 내리다, 끝나다" },
      { "en": "valid", "ko": "타당한, 유효한" },
      { "en": "validity", "ko": "타당성, 유효성" },
      { "en": "invalid", "ko": "무효한, 근거 없는, 환자" },
      { "en": "fallacy", "ko": "오류, 틀린 생각" },
      { "en": "fallacious", "ko": "잘못된, 오류가 있는" },
      { "en": "paradox", "ko": "역설, 패러독스" },
      { "en": "paradoxical", "ko": "역설적인" },
      { "en": "dilemma", "ko": "진퇴양난, 딜레마" },
      { "en": "contradict", "ko": "모순되다, 반박하다" },
      { "en": "contradiction", "ko": "모순, 반박" },
      { "en": "contradictory", "ko": "모순되는" },
      { "en": "consistent", "ko": "일관된, 부합하는" },
      { "en": "consistency", "ko": "일관성" },
      { "en": "inconsistent", "ko": "일관성 없는, 모순된" },
      { "en": "coherent", "ko": "조리 있는, 통일성 있는" },
      { "en": "coherence", "ko": "일관성, 조리" },
      { "en": "rational", "ko": "합리적인, 이성적인" },
      { "en": "rationality", "ko": "합리성, 이성" },
      { "en": "irrational", "ko": "비이성적인, 불합리한" },
      { "en": "reason", "ko": "이유, 이성, 추론하다" },
      { "en": "reasonable", "ko": "합리적인, 타당한" },
      { "en": "cause", "ko": "원인, 야기하다, 대의" },
      { "en": "causal", "ko": "인과관계의" },
      { "en": "effect", "ko": "영향, 효과, 결과" },
      { "en": "effective", "ko": "효과적인, 유효한" },
      { "en": "consequence", "ko": "결과, 중요성" },
      { "en": "consequent", "ko": "결과로 일어나는" },
      { "en": "attribute", "ko": "원인으로 돌리다, 속성" },
      { "en": "ascribe", "ko": "원인을 돌리다" },
      { "en": "factor", "ko": "요인, 인자" },
      { "en": "catalyst", "ko": "촉매, 기폭제" }
    ]
  },
  {
    "id": "wm2000_day_32",
    "book": "워드마스터 수능 2000",
    "title": "Day 32",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "linguistics", "ko": "언어학" },
      { "en": "linguistic", "ko": "언어의, 언어학의" },
      { "en": "dialect", "ko": "방언, 사투리" },
      { "en": "accent", "ko": "억양, 강세, 강조하다" },
      { "en": "pronounce", "ko": "발음하다, 선언하다" },
      { "en": "pronunciation", "ko": "발음" },
      { "en": "vocabulary", "ko": "어휘, 어휘력" },
      { "en": "grammar", "ko": "문법" },
      { "en": "grammatical", "ko": "문법적인" },
      { "en": "syntax", "ko": "통사론, 구문론" },
      { "en": "semantics", "ko": "의미론" },
      { "en": "idiom", "ko": "관용구, 숙어" },
      { "en": "idiomatic", "ko": "관용적인" },
      { "en": "slang", "ko": "속어, 은어" },
      { "en": "jargon", "ko": "전문 용어" },
      { "en": "terminology", "ko": "전문 용어 체계" },
      { "en": "fluent", "ko": "유창한, 능통한" },
      { "en": "fluency", "ko": "유창함" },
      { "en": "articulate", "ko": "또렷이 말하다, 분명한" },
      { "en": "articulation", "ko": "명확한 발음, 표현" },
      { "en": "rhetoric", "ko": "수사법, 미사여구" },
      { "en": "rhetorical", "ko": "수사적인" },
      { "en": "narrative", "ko": "이야기, 서사" },
      { "en": "narrate", "ko": "이야기하다" },
      { "en": "narrator", "ko": "서술자, 해설자" },
      { "en": "metaphor", "ko": "은유, 비유" },
      { "en": "simile", "ko": "직유, 직유법" },
      { "en": "symbolism", "ko": "상징주의, 상징적 표현" },
      { "en": "irony", "ko": "반어법, 풍자, 아이러니" },
      { "en": "satire", "ko": "풍자, 풍자 문학" },
      { "en": "parody", "ko": "패러디, 풍자적 모방" },
      { "en": "hyperbole", "ko": "과장, 과장법" },
      { "en": "euphemism", "ko": "완곡어법" },
      { "en": "cliché", "ko": "진부한 표현, 상투적 문구" },
      { "en": "quote", "ko": "인용하다, 견적을 내다" },
      { "en": "quotation", "ko": "인용, 인용구" },
      { "en": "cite", "ko": "인용하다, 언급하다" },
      { "en": "citation", "ko": "인용, 표창" },
      { "en": "paraphrase", "ko": "다른 말로 바꾸어 표현하다" },
      { "en": "summarize", "ko": "요약하다" }
    ]
  },
  {
    "id": "wm2000_day_33",
    "book": "워드마스터 수능 2000",
    "title": "Day 33",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "hierarchy", "ko": "계급 체계, 위계" },
      { "en": "hierarchical", "ko": "계급에 따른, 계층적인" },
      { "en": "stratification", "ko": "계층화, 단층화" },
      { "en": "class", "ko": "계급, 계층, 수업" },
      { "en": "status", "ko": "지위, 신분, 상태" },
      { "en": "prestige", "ko": "위신, 명성" },
      { "en": "prestigious", "ko": "명망 있는, 일류의" },
      { "en": "elite", "ko": "엘리트, 최상류층" },
      { "en": "underprivileged", "ko": "혜택을 받지 못하는" },
      { "en": "poverty", "ko": "빈곤, 가난" },
      { "en": "destitute", "ko": "극빈한, 빈곤한" },
      { "en": "impoverished", "ko": "가난해진, 궁핍한" },
      { "en": "wealth", "ko": "부, 재산, 풍부함" },
      { "en": "wealthy", "ko": "부유한, 재산이 많은" },
      { "en": "affluent", "ko": "부유한, 풍요로운" },
      { "en": "affluence", "ko": "풍요, 부유" },
      { "en": "prosperity", "ko": "번영, 번성" },
      { "en": "prosper", "ko": "번영하다, 번창하다" },
      { "en": "prosperous", "ko": "번영하는, 번성한" },
      { "en": "welfare", "ko": "복지, 안녕" },
      { "en": "wellbeing", "ko": "행복, 안녕" },
      { "en": "subsidy", "ko": "보조금, 장려금" },
      { "en": "subsidize", "ko": "보조금을 지급하다" },
      { "en": "pension", "ko": "국민연금, 연금" },
      { "en": "insurance", "ko": "보험" },
      { "en": "inequality", "ko": "불평등" },
      { "en": "equality", "ko": "평등" },
      { "en": "equity", "ko": "공평, 공정, 자기자본" },
      { "en": "discrimination", "ko": "차별, 분별력" },
      { "en": "discriminate", "ko": "차별하다, 구별하다" },
      { "en": "segregation", "ko": "인종 차별, 격리" },
      { "en": "segregate", "ko": "격리하다, 분리하다" },
      { "en": "integrate", "ko": "통합하다, 융합하다" },
      { "en": "integration", "ko": "통합" },
      { "en": "marginalize", "ko": "사회적으로 소외시키다" },
      { "en": "minority", "ko": "소수자, 소수" },
      { "en": "majority", "ko": "다수, 과반수" },
      { "en": "diversity", "ko": "다양성" },
      { "en": "diverse", "ko": "다양한" },
      { "en": "multicultural", "ko": "다문화의" }
    ]
  },
  {
    "id": "wm2000_day_34",
    "book": "워드마스터 수능 2000",
    "title": "Day 34",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "melody", "ko": "선율, 멜로디" },
      { "en": "harmony", "ko": "화음, 조화" },
      { "en": "rhythm", "ko": "리듬, 규칙적 변화" },
      { "en": "rhythmic", "ko": "리듬감 있는" },
      { "en": "tempo", "ko": "속도, 템포" },
      { "en": "composition", "ko": "작곡, 구성, 작품" },
      { "en": "composer", "ko": "작곡가" },
      { "en": "orchestra", "ko": "오케스트라, 관현악단" },
      { "en": "symphony", "ko": "교향곡" },
      { "en": "concerto", "ko": "협주곡" },
      { "en": "conductor", "ko": "지휘자, 전도체" },
      { "en": "instrumental", "ko": "기악의, 도움이 되는" },
      { "en": "vocal", "ko": "목소리의, 성악의, 의견을 강력히 밝히는" },
      { "en": "vocalist", "ko": "가수, 보컬" },
      { "en": "choir", "ko": "합창단, 성가대" },
      { "en": "chorus", "ko": "합창, 후렴구" },
      { "en": "audition", "ko": "오디션, 심사" },
      { "en": "rehearse", "ko": "연습하다, 리허설을 하다" },
      { "en": "rehearsal", "ko": "리허설, 예행연습" },
      { "en": "venue", "ko": "공연 장소, 개최지" },
      { "en": "stage", "ko": "무대, 단계" },
      { "en": "backdrop", "ko": "배경, 배경막" },
      { "en": "costume", "ko": "의상, 복장" },
      { "en": "prop", "ko": "소품, 받침대, 지지하다" },
      { "en": "script", "ko": "대본, 원고" },
      { "en": "playwright", "ko": "극작가" },
      { "en": "director", "ko": "감독, 연출가, 이사" },
      { "en": "choreography", "ko": "안무, 무용 지도" },
      { "en": "choreographer", "ko": "안무가" },
      { "en": "spectator", "ko": "관객, 관중" },
      { "en": "applause", "ko": "박수갈채" },
      { "en": "applaud", "ko": "박수치다, 칭찬하다" },
      { "en": "ovation", "ko": "열렬한 박수, 환호" },
      { "en": "encore", "ko": "앙코르, 재공연 요청" },
      { "en": "debut", "ko": "데뷔, 첫 등장" },
      { "en": "celebrity", "ko": "유명인, 명성" },
      { "en": "entertainment", "ko": "오락, 연예" },
      { "en": "entertainer", "ko": "연예인" },
      { "en": "amuse", "ko": "즐겁게 하다" },
      { "en": "amusement", "ko": "재미, 오락" }
    ]
  },
  {
    "id": "wm2000_day_35",
    "book": "워드마스터 수능 2000",
    "title": "Day 35",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "commerce", "ko": "상업, 교역" },
      { "en": "commercialize", "ko": "상업화하다" },
      { "en": "merchandise", "ko": "상품, 물품" },
      { "en": "commodity", "ko": "원자재, 상품" },
      { "en": "inventory", "ko": "재고, 재고 목록" },
      { "en": "stock", "ko": "재고, 주식, 저장하다" },
      { "en": "wholesale", "ko": "도매, 도매의" },
      { "en": "retail", "ko": "소매, 소매의" },
      { "en": "retailer", "ko": "소매상, 유통업체" },
      { "en": "distribute", "ko": "유통하다, 배분하다" },
      { "en": "distribution", "ko": "유통, 분배" },
      { "en": "distributor", "ko": "유통업자, 배급사" },
      { "en": "logistics", "ko": "물류, 물류 관리" },
      { "en": "supply", "ko": "공급, 공급하다" },
      { "en": "demand", "ko": "수요, 요구하다" },
      { "en": "consumer", "ko": "소비자" },
      { "en": "consume", "ko": "소비하다, 소모하다" },
      { "en": "consumption", "ko": "소비, 소비량" },
      { "en": "advertisement", "ko": "광고, 홍보" },
      { "en": "advertise", "ko": "광고하다" },
      { "en": "brand", "ko": "상표, 브랜드" },
      { "en": "reputation", "ko": "평판, 명성" },
      { "en": "loyalty", "ko": "충성도, 충성심" },
      { "en": "customer", "ko": "고객, 손님" },
      { "en": "client", "ko": "고객, 의뢰인" },
      { "en": "transaction", "ko": "거래, 매매" },
      { "en": "receipt", "ko": "영수증, 수령" },
      { "en": "refund", "ko": "환불, 환불하다" },
      { "en": "exchange", "ko": "교환하다, 환전하다" },
      { "en": "warranty", "ko": "품질 보증서" },
      { "en": "guarantee", "ko": "보장하다, 보증" },
      { "en": "discount", "ko": "할인, 무시하다" },
      { "en": "bargain", "ko": "특가품, 흥정하다" },
      { "en": "auction", "ko": "경매" },
      { "en": "bid", "ko": "입찰하다, 입찰" },
      { "en": "monopoly", "ko": "독점, 전매" },
      { "en": "oligopoly", "ko": "과점" },
      { "en": "competition", "ko": "경쟁" },
      { "en": "competitor", "ko": "경쟁자, 경쟁업체" },
      { "en": "niche", "ko": "틈새시장, 적소" }
    ]
  },
  {
    "id": "wm2000_day_36",
    "book": "워드마스터 수능 2000",
    "title": "Day 36",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "chemistry", "ko": "화학" },
      { "en": "chemical", "ko": "화학 물질, 화학의" },
      { "en": "element", "ko": "원소, 요소" },
      { "en": "compound", "ko": "화합물, 혼합하다" },
      { "en": "reaction", "ko": "반응" },
      { "en": "react", "ko": "반응하다" },
      { "en": "reactant", "ko": "반응 물질" },
      { "en": "catalyst", "ko": "촉매" },
      { "en": "solution", "ko": "용액, 해결책" },
      { "en": "solvent", "ko": "용매, 지불 능력이 있는" },
      { "en": "solute", "ko": "용질" },
      { "en": "dissolve", "ko": "녹이다, 용해하다" },
      { "en": "acid", "ko": "산, 산성의" },
      { "en": "acidic", "ko": "산성의" },
      { "en": "alkali", "ko": "알칼리, 염기" },
      { "en": "alkaline", "ko": "알칼리성의" },
      { "en": "neutral", "ko": "중성의, 중립의" },
      { "en": "neutralize", "ko": "중화하다, 무력화하다" },
      { "en": "thermodynamics", "ko": "열역학" },
      { "en": "thermal", "ko": "열의, 보온의" },
      { "en": "kinetic", "ko": "운동의, 운동 에너지의" },
      { "en": "potential", "ko": "잠재력, 잠재적인, 위치 에너지" },
      { "en": "friction", "ko": "마찰력, 저항" },
      { "en": "inertia", "ko": "관성, 무기력" },
      { "en": "momentum", "ko": "운동량, 추진력" },
      { "en": "equilibrium", "ko": "평형 상태, 균형" },
      { "en": "optics", "ko": "광학" },
      { "en": "refract", "ko": "굴절시키다" },
      { "en": "refraction", "ko": "굴절" },
      { "en": "reflect", "ko": "반사하다, 반영하다, 숙고하다" },
      { "en": "reflection", "ko": "반사, 반영, 심사숙고" },
      { "en": "transmit", "ko": "투과시키다, 전송하다" },
      { "en": "absorb", "ko": "흡수하다, 열중시키다" },
      { "en": "absorption", "ko": "흡수, 몰입" },
      { "en": "fluid", "ko": "유체, 유동적인" },
      { "en": "liquify", "ko": "액화하다" },
      { "en": "evaporate", "ko": "증발하다, 사라지다" },
      { "en": "evaporation", "ko": "증발" },
      { "en": "condense", "ko": "응결되다, 요약하다" },
      { "en": "condensation", "ko": "응결, 응축" }
    ]
  },
  {
    "id": "wm2000_day_37",
    "book": "워드마스터 수능 2000",
    "title": "Day 37",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "behavior", "ko": "행동, 처신" },
      { "en": "behavioral", "ko": "행동의" },
      { "en": "habit", "ko": "습관, 버릇" },
      { "en": "habitual", "ko": "습관적인, 늘 하는" },
      { "en": "routine", "ko": "일상, 판에 박힌 일" },
      { "en": "stimulus", "ko": "자극" },
      { "en": "stimulate", "ko": "자극하다, 격려하다" },
      { "en": "stimulation", "ko": "자극, 흥분" },
      { "en": "response", "ko": "반응, 응답" },
      { "en": "conditioned", "ko": "조건 반사의, 길들여진" },
      { "en": "reinforce", "ko": "강화하다, 보강하다" },
      { "en": "reinforcement", "ko": "강화, 보강" },
      { "en": "extinction", "ko": "소거, 소멸" },
      { "en": "instinct", "ko": "본능, 직관" },
      { "en": "instinctive", "ko": "본능적인" },
      { "en": "intuition", "ko": "직관" },
      { "en": "subconscious", "ko": "잠재의식, 잠재의식적인" },
      { "en": "unconscious", "ko": "무의식적인" },
      { "en": "repression", "ko": "억압, 억제" },
      { "en": "repress", "ko": "억압하다, 억누르다" },
      { "en": "defense", "ko": "방어, 변호" },
      { "en": "mechanism", "ko": "기제, 메커니즘, 구조" },
      { "en": "projection", "ko": "투사, 예상, 투영" },
      { "en": "introvert", "ko": "내향적인 사람" },
      { "en": "introverted", "ko": "내향적인" },
      { "en": "extrovert", "ko": "외향적인 사람" },
      { "en": "extroverted", "ko": "외향적인" },
      { "en": "self-esteem", "ko": "자존감, 자부심" },
      { "en": "self-efficacy", "ko": "자기효능감" },
      { "en": "narcissism", "ko": "자기애, 나르시시즘" },
      { "en": "complex", "ko": "콤플렉스, 강박관념" },
      { "en": "trauma", "ko": "정신적 충격, 트라우마" },
      { "en": "neurosis", "ko": "신경증, 노이로제" },
      { "en": "psychosis", "ko": "정신병" },
      { "en": "therapy", "ko": "심리 치료, 요법" },
      { "en": "counseling", "ko": "상담, 조언" },
      { "en": "consult", "ko": "상담하다, 상의하다" },
      { "en": "consultant", "ko": "상담가, 자문위원" },
      { "en": "coping", "ko": "대처, 대응" },
      { "en": "cope", "ko": "대처하다, 맞서다" }
    ]
  },
  {
    "id": "wm2000_day_38",
    "book": "워드마스터 수능 2000",
    "title": "Day 38",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "pedagogy", "ko": "교육학, 교수법" },
      { "en": "didactic", "ko": "교훈적인, 가르치려 드는" },
      { "en": "mentor", "ko": "멘토, 조언자" },
      { "en": "mentorship", "ko": "멘토 관계, 지도" },
      { "en": "tutor", "ko": "개인 지도 교사, 지도하다" },
      { "en": "tutorial", "ko": "개별 지도, 사용 지침서" },
      { "en": "scholar", "ko": "학자" },
      { "en": "scholastic", "ko": "학업의, 학교의" },
      { "en": "erudite", "ko": "박식한, 학식 있는" },
      { "en": "literacy", "ko": "문해력, 읽고 쓰는 능력" },
      { "en": "numeracy", "ko": "산술 능력, 수리력" },
      { "en": "critical", "ko": "비판적인, 중요한" },
      { "en": "inquiry", "ko": "탐구, 질문, 문의" },
      { "en": "inquire", "ko": "묻다, 조사하다" },
      { "en": "investigate", "ko": "연구하다, 조사하다" },
      { "en": "methodology", "ko": "방법론" },
      { "en": "empirical", "ko": "경험적인, 실증적인" },
      { "en": "quantitative", "ko": "양적인, 수량적인" },
      { "en": "qualitative", "ko": "질적인" },
      { "en": "sample", "ko": "표본, 견본" },
      { "en": "sampling", "ko": "표본 추출" },
      { "en": "survey", "ko": "설문 조사, 조망하다" },
      { "en": "questionnaire", "ko": "질문지, 설문지" },
      { "en": "correlation", "ko": "상관관계" },
      { "en": "causation", "ko": "인과관계" },
      { "en": "bias", "ko": "편향, 선입견" },
      { "en": "prejudice", "ko": "편견, 선입관" },
      { "en": "peer-review", "ko": "동료 심사" },
      { "en": "citation", "ko": "인용" },
      { "en": "bibliography", "ko": "참고문헌 목록" },
      { "en": "abstract", "ko": "초록, 개요, 추상적인" },
      { "en": "thesis", "ko": "학위 논문, 명제" },
      { "en": "dissertation", "ko": "박사 논문" },
      { "en": "plagiarism", "ko": "표절" },
      { "en": "plagiarize", "ko": "표절하다" },
      { "en": "ethics", "ko": "연구 윤리, 윤리학" },
      { "en": "integrity", "ko": "진실성, 온전함" },
      { "en": "rigorous", "ko": "엄격한, 철저한" },
      { "en": "rigor", "ko": "엄격함, 정확함" },
      { "en": "academician", "ko": "학술원 회원, 학자" }
    ]
  },
  {
    "id": "wm2000_day_39",
    "book": "워드마스터 수능 2000",
    "title": "Day 39",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "pharmacy", "ko": "약국, 약학" },
      { "en": "pharmaceutical", "ko": "제약의, 약학의" },
      { "en": "pharmacist", "ko": "약사" },
      { "en": "prescription", "ko": "처방전, 규정" },
      { "en": "prescribe", "ko": "처방하다, 규정하다" },
      { "en": "dosage", "ko": "복용량, 투약량" },
      { "en": "dose", "ko": "1회 복용량" },
      { "en": "medication", "ko": "약물, 투약" },
      { "en": "antibiotic", "ko": "항생제" },
      { "en": "antiviral", "ko": "항바이러스의" },
      { "en": "painkiller", "ko": "진통제" },
      { "en": "sedative", "ko": "진정제" },
      { "en": "anesthetic", "ko": "마취제, 마취의" },
      { "en": "anesthesia", "ko": "마취" },
      { "en": "surgery", "ko": "수술, 외과" },
      { "en": "surgeon", "ko": "외과의사" },
      { "en": "surgical", "ko": "수술의, 외과의" },
      { "en": "operation", "ko": "수술, 작동, 운영" },
      { "en": "operate", "ko": "수술하다, 작동하다" },
      { "en": "transplant", "ko": "이식하다, 장기 이식" },
      { "en": "donor", "ko": "기증자, 기부자" },
      { "en": "recipient", "ko": "수혜자, 장기 이식 받는 사람" },
      { "en": "chronic", "ko": "만성의" },
      { "en": "acute", "ko": "급성의, 예리한" },
      { "en": "malignant", "ko": "악성의 (종양)" },
      { "en": "benign", "ko": "양성의, 온화한" },
      { "en": "tumor", "ko": "종양" },
      { "en": "cancer", "ko": "암" },
      { "en": "carcinogen", "ko": "발암 물질" },
      { "en": "hypertension", "ko": "고혈압" },
      { "en": "diabetes", "ko": "당뇨병" },
      { "en": "stroke", "ko": "뇌졸중, 타격" },
      { "en": "cardiac", "ko": "심장의" },
      { "en": "respiratory", "ko": "호흡기의" },
      { "en": "asthma", "ko": "천식" },
      { "en": "allergy", "ko": "알레르기" },
      { "en": "allergic", "ko": "알레르기가 있는" },
      { "en": "rehabilitation", "ko": "재활, 사회 복귀" },
      { "en": "rehabilitate", "ko": "재활 치료를 하다" },
      { "en": "prognosis", "ko": "예후, 예측" }
    ]
  },
  {
    "id": "wm2000_day_40",
    "book": "워드마스터 수능 2000",
    "title": "Day 40",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "sustainability", "ko": "지속 가능성" },
      { "en": "renewable", "ko": "재생 가능한" },
      { "en": "biofuel", "ko": "바이오 연료" },
      { "en": "solar", "ko": "태양광의" },
      { "en": "photovoltaic", "ko": "태양광 발전의" },
      { "en": "hydroelectric", "ko": "수력 발전의" },
      { "en": "geothermal", "ko": "지열의" },
      { "en": "deforestation", "ko": "삼림 벌채, 산림 파괴" },
      { "en": "afforestation", "ko": "조림, 숲 가꾸기" },
      { "en": "desertification", "ko": "사막화" },
      { "en": "biodiversity", "ko": "생물다양성" },
      { "en": "degradation", "ko": "퇴화, 질적 저하" },
      { "en": "degrade", "ko": "분해되다, 저하시키다" },
      { "en": "biodegradable", "ko": "생분해성의" },
      { "en": "footprint", "ko": "발자국, 탄소 발자국" },
      { "en": "carbon", "ko": "탄소" },
      { "en": "greenhouse", "ko": "온실" },
      { "en": "ozone", "ko": "오존" },
      { "en": "depletion", "ko": "고갈, 소모" },
      { "en": "deplete", "ko": "고갈시키다" },
      { "en": "acid rain", "ko": "산성비" },
      { "en": "smog", "ko": "스모그" },
      { "en": "particulate", "ko": "미립자, 미세먼지" },
      { "en": "landfill", "ko": "쓰레기 매립지" },
      { "en": "incinerate", "ko": "소각하다" },
      { "en": "incineration", "ko": "소각, 전소" },
      { "en": "conservationist", "ko": "자연보호 활동가" },
      { "en": "activist", "ko": "활동가, 운동가" },
      { "en": "legislation", "ko": "법률 제정, 입법" },
      { "en": "protocol", "ko": "의정서, 협약" },
      { "en": "treaty", "ko": "조약" },
      { "en": "regulation", "ko": "규제, 단속" },
      { "en": "regulate", "ko": "규제하다, 조절하다" },
      { "en": "sanctuary", "ko": "보호구역, 안식처" },
      { "en": "wildlife", "ko": "야생동물" },
      { "en": "poach", "ko": "밀렵하다" },
      { "en": "poacher", "ko": "밀렵꾼" },
      { "en": "endangered", "ko": "멸종 위기에 처한" },
      { "en": "threatened", "ko": "위협받는" },
      { "en": "extinction", "ko": "멸종, 사멸" }
    ]
  },
  {
    "id": "wm2000_day_41",
    "book": "워드마스터 수능 2000",
    "title": "Day 41",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "civilization", "ko": "문명" },
      { "en": "civilize", "ko": "문명화하다" },
      { "en": "ancient", "ko": "고대의, 옛날의" },
      { "en": "medieval", "ko": "중세의" },
      { "en": "renaissance", "ko": "부흥, 르네상스" },
      { "en": "revolution", "ko": "혁명, 변혁" },
      { "en": "revolutionary", "ko": "혁명적인, 혁명가" },
      { "en": "rebellion", "ko": "반란, 반역" },
      { "en": "rebel", "ko": "반역자, 반란을 일으키다" },
      { "en": "uprising", "ko": "봉기, 반란" },
      { "en": "empire", "ko": "제국" },
      { "en": "emperor", "ko": "황제" },
      { "en": "imperial", "ko": "제국의, 황제의" },
      { "en": "imperialism", "ko": "제국주의" },
      { "en": "colony", "ko": "식민지" },
      { "en": "colonial", "ko": "식민지의" },
      { "en": "colonize", "ko": "식민지화하다" },
      { "en": "independence", "ko": "독립, 자립" },
      { "en": "archaeology", "ko": "고고학" },
      { "en": "archaeologist", "ko": "고고학자" },
      { "en": "excavate", "ko": "발굴하다, 파내다" },
      { "en": "excavation", "ko": "발굴, 출토품" },
      { "en": "artifact", "ko": "유물, 인공물" },
      { "en": "relic", "ko": "유물, 유적" },
      { "en": "ruins", "ko": "폐허, 유적" },
      { "en": "fossilize", "ko": "화석화하다" },
      { "en": "dynasty", "ko": "왕조, 시대" },
      { "en": "reign", "ko": "통치 기간, 군림하다" },
      { "en": "monarch", "ko": "군주" },
      { "en": "sovereign", "ko": "주권자, 통치자, 주권이 있는" },
      { "en": "sovereignty", "ko": "주권, 통치권" },
      { "en": "chronicle", "ko": "연대기, 기록하다" },
      { "en": "archive", "ko": "기록 보관소, 공문서" },
      { "en": "monument", "ko": "기념물, 기념비" },
      { "en": "inscribe", "ko": "새기다, 쓰다" },
      { "en": "inscription", "ko": "비문, 새긴 글" },
      { "en": "heritage", "ko": "문화유산" },
      { "en": "legacy", "ko": "유산, 물려받은 것" },
      { "en": "prehistoric", "ko": "선사 시대의" },
      { "en": "primitive", "ko": "원시의, 초기의" }
    ]
  },
  {
    "id": "wm2000_day_42",
    "book": "워드마스터 수능 2000",
    "title": "Day 42",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "diplomacy", "ko": "외교, 외교술" },
      { "en": "diplomat", "ko": "외교관" },
      { "en": "diplomatic", "ko": "외교의, 수완 있는" },
      { "en": "ambassador", "ko": "대사, 특사" },
      { "en": "embassy", "ko": "대사관" },
      { "en": "consulate", "ko": "영사관" },
      { "en": "envoy", "ko": "특사, 사절" },
      { "en": "negotiator", "ko": "협상가" },
      { "en": "bilateral", "ko": "양국의, 쌍방의" },
      { "en": "multilateral", "ko": "다국간의, 다자간의" },
      { "en": "accord", "ko": "협정, 합의, 부여하다" },
      { "en": "alliance", "ko": "동맹, 연합" },
      { "en": "coalition", "ko": "연립 정부, 연합" },
      { "en": "summit", "ko": "정상회담, 정상, 꼭대기" },
      { "en": "convention", "ko": "관례, 협약, 총회" },
      { "en": "treaty", "ko": "조약" },
      { "en": "ratify", "ko": "비준하다, 승인하다" },
      { "en": "ratification", "ko": "비준, 승인" },
      { "en": "sanction", "ko": "제재, 인가, 허가하다" },
      { "en": "embargo", "ko": "통상 금지령, 금수 조치" },
      { "en": "boycott", "ko": "불매 운동을 벌이다" },
      { "en": "neutrality", "ko": "중립, 중립성" },
      { "en": "neutral", "ko": "중립의" },
      { "en": "nonalignment", "ko": "비동맹" },
      { "en": "hegemony", "ko": "패권, 주도권" },
      { "en": "superpower", "ko": "초강대국" },
      { "en": "sovereignty", "ko": "주권, 자주권" },
      { "en": "autonomy", "ko": "자치권, 자율성" },
      { "en": "autonomous", "ko": "자치의, 자율적인" },
      { "en": "regime", "ko": "정권, 제도" },
      { "en": "administration", "ko": "행정부, 관리" },
      { "en": "bureaucracy", "ko": "관료제, 관료주의" },
      { "en": "bureaucrat", "ko": "관료" },
      { "en": "corrupt", "ko": "부패한, 부패시키다" },
      { "en": "corruption", "ko": "부패, 비리" },
      { "en": "bribe", "ko": "뇌물, 뇌물을 주다" },
      { "en": "bribery", "ko": "뇌물 수수" },
      { "en": "transparency", "ko": "투명성, 명백함" },
      { "en": "transparent", "ko": "투명한, 명백한" },
      { "en": "accountability", "ko": "책임, 의무" }
    ]
  },
  {
    "id": "wm2000_day_43",
    "book": "워드마스터 수능 2000",
    "title": "Day 43",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "infancy", "ko": "유아기, 초기" },
      { "en": "infant", "ko": "유아, 젖먹이" },
      { "en": "toddler", "ko": "걸음마를 배우는 아이" },
      { "en": "childhood", "ko": "유년기, 어린 시절" },
      { "en": "adolescence", "ko": "청소년기, 사춘기" },
      { "en": "adolescent", "ko": "청소년" },
      { "en": "puberty", "ko": "사춘기" },
      { "en": "youth", "ko": "젊음, 청년" },
      { "en": "juvenile", "ko": "청소년의, 유치한" },
      { "en": "adulthood", "ko": "성인기, 성인임" },
      { "en": "adult", "ko": "성인, 성숙한" },
      { "en": "mature", "ko": "성숙한, 익다" },
      { "en": "maturity", "ko": "성숙, 만기" },
      { "en": "immature", "ko": "미성숙한" },
      { "en": "aging", "ko": "노화, 나이 먹음" },
      { "en": "elderly", "ko": "나이 든, 어르신" },
      { "en": "senior", "ko": "고령자, 선배, 고위의" },
      { "en": "longevity", "ko": "장수, 수명" },
      { "en": "lifespan", "ko": "수명, 생존 기간" },
      { "en": "life expectancy", "ko": "기대 수명" },
      { "en": "retiree", "ko": "퇴직자, 은퇴자" },
      { "en": "senile", "ko": "노망든, 노쇠한" },
      { "en": "dementia", "ko": "치매" },
      { "en": "cognitive decline", "ko": "인지 저하" },
      { "en": "developmental", "ko": "발달의, 발달상의" },
      { "en": "milestone", "ko": "중요한 이정표, 획기적 사건" },
      { "en": "nurture", "ko": "양육하다, 보살피다" },
      { "en": "foster", "ko": "양육하다, 촉진하다" },
      { "en": "parenting", "ko": "육아, 부모 노릇" },
      { "en": "upbringing", "ko": "양육, 훈육" },
      { "en": "socialization", "ko": "사회화" },
      { "en": "peer pressure", "ko": "또래 압력" },
      { "en": "identity", "ko": "정체성, 신원" },
      { "en": "individuality", "ko": "개성, 개별성" },
      { "en": "role model", "ko": "본보기가 되는 사람" },
      { "en": "generation gap", "ko": "세대 차이" },
      { "en": "filial", "ko": "자식의, 효성스러운" },
      { "en": "ancestral", "ko": "조상의, 선조의" },
      { "en": "kinship", "ko": "친족 관계, 유대감" },
      { "en": "descendant", "ko": "자손, 후예" }
    ]
  },
  {
    "id": "wm2000_day_44",
    "book": "워드마스터 수능 2000",
    "title": "Day 44",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "artificial intelligence", "ko": "인공지능" },
      { "en": "machine learning", "ko": "기계 학습, 머신러닝" },
      { "en": "neural network", "ko": "신경망" },
      { "en": "algorithm", "ko": "알고리즘" },
      { "en": "robotics", "ko": "로봇공학" },
      { "en": "robot", "ko": "로봇" },
      { "en": "autonomous", "ko": "자율적인, 자율 주행의" },
      { "en": "automation", "ko": "자동화" },
      { "en": "automate", "ko": "자동화하다" },
      { "en": "sensor", "ko": "센서, 감지기" },
      { "en": "actuator", "ko": "작동기, 구동 장치" },
      { "en": "nanotechnology", "ko": "나노기술" },
      { "en": "biotechnology", "ko": "생명공학" },
      { "en": "genetic engineering", "ko": "유전공학" },
      { "en": "virtual reality", "ko": "가상현실" },
      { "en": "augmented reality", "ko": "증강현실" },
      { "en": "cyberspace", "ko": "가상공간, 사이버공간" },
      { "en": "quantum", "ko": "양자, 양자의" },
      { "en": "computation", "ko": "계산, 연산" },
      { "en": "cloud computing", "ko": "클라우드 컴퓨팅" },
      { "en": "big data", "ko": "빅데이터" },
      { "en": "data mining", "ko": "데이터 마이닝, 정보 추출" },
      { "en": "predictive", "ko": "예측의, 예언하는" },
      { "en": "simulation", "ko": "시뮬레이션, 모의실험" },
      { "en": "simulate", "ko": "모의실험을 하다" },
      { "en": "prototype", "ko": "시제품, 견본" },
      { "en": "disruptive", "ko": "파괴적인, 혁신적인" },
      { "en": "breakthrough", "ko": "비약적 발전, 돌파구" },
      { "en": "frontier", "ko": "최첨단 영역, 국경" },
      { "en": "cutting-edge", "ko": "최첨단의" },
      { "en": "state-of-the-art", "ko": "최신식의, 최고 수준의" },
      { "en": "obsolete", "ko": "더 이상 쓸모없는, 구식의" },
      { "en": "outdated", "ko": "구식의, 시대에 뒤떨어진" },
      { "en": "upgrade", "ko": "업그레이드하다, 향상시키다" },
      { "en": "downgrade", "ko": "격하시키다" },
      { "en": "compatible", "ko": "호환되는, 양립할 수 있는" },
      { "en": "compatibility", "ko": "호환성, 융합성" },
      { "en": "telecommunication", "ko": "원격 통신" },
      { "en": "broadband", "ko": "광대역 통신망" },
      { "en": "bandwidth", "ko": "대역폭, 처리 용량" }
    ]
  },
  {
    "id": "wm2000_day_45",
    "book": "워드마스터 수능 2000",
    "title": "Day 45",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "fiction", "ko": "소설, 허구" },
      { "en": "fictional", "ko": "허구의, 가상의" },
      { "en": "nonfiction", "ko": "논픽션, 비소설" },
      { "en": "novel", "ko": "소설, 참신한" },
      { "en": "novelist", "ko": "소설가" },
      { "en": "poetry", "ko": "시, 시가" },
      { "en": "poem", "ko": "시 (개별 작품)" },
      { "en": "poet", "ko": "시인" },
      { "en": "poetic", "ko": "시적인" },
      { "en": "prose", "ko": "산문, 산문체" },
      { "en": "drama", "ko": "희곡, 드라마" },
      { "en": "dramatic", "ko": "극적인, 연극의" },
      { "en": "playwright", "ko": "극작가" },
      { "en": "tragedy", "ko": "비극, 비극적 사건" },
      { "en": "tragic", "ko": "비극적인" },
      { "en": "comedy", "ko": "희극, 코미디" },
      { "en": "comic", "ko": "희극의, 만화" },
      { "en": "satire", "ko": "풍자" },
      { "en": "satirical", "ko": "풍자적인" },
      { "en": "irony", "ko": "아이러니, 반어법" },
      { "en": "protagonist", "ko": "주인공" },
      { "en": "antagonist", "ko": "적대자, 악역" },
      { "en": "plot", "ko": "줄거리, 구성, 음모" },
      { "en": "climax", "ko": "절정, 클라이맥스" },
      { "en": "theme", "ko": "주제, 테마" },
      { "en": "motif", "ko": "동기, 모티프, 문양" },
      { "en": "symbolism", "ko": "상징적 의미, 상징주의" },
      { "en": "allusion", "ko": "암시, 인용" },
      { "en": "foreshadow", "ko": "복선을 깔다, 암시하다" },
      { "en": "flashback", "ko": "회상 장면, 플래시백" },
      { "en": "narrator", "ko": "서술자, 해설자" },
      { "en": "perspective", "ko": "시점, 관점, 원근법" },
      { "en": "first-person", "ko": "1인칭의" },
      { "en": "omniscient", "ko": "전지전능한, 모든 것을 아는" },
      { "en": "setting", "ko": "배경, 설정" },
      { "en": "dialogue", "ko": "대화" },
      { "en": "monologue", "ko": "독백" },
      { "en": "soliloquy", "ko": "독백" },
      { "en": "aesthetic", "ko": "미적인, 심미적인" },
      { "en": "criticism", "ko": "비평, 비판" }
    ]
  },
  {
    "id": "wm2000_day_46",
    "book": "워드마스터 수능 2000",
    "title": "Day 46",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "bias", "ko": "편향, 치우침" },
      { "en": "prejudice", "ko": "선입견, 편견" },
      { "en": "stereotype", "ko": "고정관념" },
      { "en": "cognitive dissonance", "ko": "인지 부조화" },
      { "en": "confirmation bias", "ko": "확증 편향" },
      { "en": "heuristic", "ko": "어림셈, 발견적 교수법" },
      { "en": "fallacy", "ko": "오류, 그릇된 논리" },
      { "en": "rationalize", "ko": "합리화하다" },
      { "en": "rationalization", "ko": "합리화" },
      { "en": "justification", "ko": "정당화, 변명" },
      { "en": "justify", "ko": "정당화하다" },
      { "en": "subjective", "ko": "주관적인" },
      { "en": "subjectivity", "ko": "주관성" },
      { "en": "objective", "ko": "객관적인, 목표" },
      { "en": "objectivity", "ko": "객관성" },
      { "en": "illusion", "ko": "착각, 환상" },
      { "en": "delusion", "ko": "망상, 착각" },
      { "en": "hallucination", "ko": "환각, 환영" },
      { "en": "deception", "ko": "속임수, 사기" },
      { "en": "deceive", "ko": "속이다, 기만하다" },
      { "en": "fallible", "ko": "실수를 저지르기 쉬운" },
      { "en": "infallible", "ko": "결코 틀리지 않는" },
      { "en": "judgment", "ko": "판단, 판결" },
      { "en": "misjudge", "ko": "잘못 판단하다" },
      { "en": "overestimate", "ko": "과대평가하다" },
      { "en": "underestimate", "ko": "과소평가하다" },
      { "en": "perspective", "ko": "시각, 견해" },
      { "en": "standpoint", "ko": "견지, 관점" },
      { "en": "viewpoint", "ko": "관점, 시각" },
      { "en": "worldview", "ko": "세계관" },
      { "en": "paradigm", "ko": "패러다임, 전형적인 예" },
      { "en": "dogma", "ko": "교조, 독단" },
      { "en": "dogmatic", "ko": "독단적인" },
      { "en": "orthodox", "ko": "정통의, 정설의" },
      { "en": "unorthodox", "ko": "이단의, 파격적인" },
      { "en": "skeptic", "ko": "회의론자" },
      { "en": "skepticism", "ko": "회의론, 의심" },
      { "en": "cynic", "ko": "냉소적인 사람" },
      { "en": "cynicism", "ko": "냉소주의" },
      { "en": "pragmatic", "ko": "실용적인, 실무적인" }
    ]
  },
  {
    "id": "wm2000_day_47",
    "book": "워드마스터 수능 2000",
    "title": "Day 47",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "urbanization", "ko": "도시화" },
      { "en": "demography", "ko": "인구통계학" },
      { "en": "demographic", "ko": "인구통계학의" },
      { "en": "population", "ko": "인구, 주민" },
      { "en": "density", "ko": "밀도" },
      { "en": "overcrowding", "ko": "과밀, 과밀화" },
      { "en": "congestion", "ko": "혼잡, 정체" },
      { "en": "slum", "ko": "빈민가, 슬럼" },
      { "en": "gentrification", "ko": "젠트리피케이션, 도시 재활성화" },
      { "en": "redevelopment", "ko": "재개발" },
      { "en": "revitalization", "ko": "재활성화, 부흥" },
      { "en": "infrastructure", "ko": "기반시설" },
      { "en": "sanitation", "ko": "공중위생, 하수 시설" },
      { "en": "sewage", "ko": "하수, 오수" },
      { "en": "drainage", "ko": "배수 시설" },
      { "en": "public transport", "ko": "대중교통" },
      { "en": "commuter", "ko": "통근자" },
      { "en": "suburbia", "ko": "교외, 교외 주민들" },
      { "en": "sprawl", "ko": "무질서한 팽창, 뻗어나가다" },
      { "en": "megalopolis", "ko": "거대 도시권" },
      { "en": "metropolis", "ko": "주요 도시, 대도시" },
      { "en": "provincial", "ko": "지방의, 편협한" },
      { "en": "hinterland", "ko": "배후지, 오지" },
      { "en": "zoning", "ko": "용도 지역 지정" },
      { "en": "ordinance", "ko": "조례, 법령" },
      { "en": "civic", "ko": "시민의, 시의" },
      { "en": "municipal", "ko": "지방자치의, 시의" },
      { "en": "municipality", "ko": "지방자치단체" },
      { "en": "amenity", "ko": "생활 편의 시설" },
      { "en": "accessibility", "ko": "접근성" },
      { "en": "livability", "ko": "거주 적합성" },
      { "en": "walkability", "ko": "보행 편의성" },
      { "en": "footpath", "ko": "보도, 오솔길" },
      { "en": "pedestrian zone", "ko": "보행자 전용 구역" },
      { "en": "green space", "ko": "녹지 공간" },
      { "en": "parkland", "ko": "공원 부지" },
      { "en": "civic center", "ko": "시민 센터" },
      { "en": "waterfront", "ko": "수변 지역, 해안가" },
      { "en": "skyline", "ko": "스카이라인, 공중선" },
      { "en": "landmark", "ko": "주요 지형지물, 랜드마크" }
    ]
  },
  {
    "id": "wm2000_day_48",
    "book": "워드마스터 수능 2000",
    "title": "Day 48",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "corporate governance", "ko": "기업 지배구조" },
      { "en": "stakeholder", "ko": "이해관계자" },
      { "en": "shareholder", "ko": "주주" },
      { "en": "stockholder", "ko": "주주" },
      { "en": "dividend", "ko": "배당금" },
      { "en": "board of directors", "ko": "이사회" },
      { "en": "audit", "ko": "회계 감사, 심사하다" },
      { "en": "auditor", "ko": "회계 감사관" },
      { "en": "compliance", "ko": "준법 감시, 규정 준수" },
      { "en": "whistleblower", "ko": "내부고발자" },
      { "en": "fraud", "ko": "사기, 사기꾼" },
      { "en": "embezzlement", "ko": "횡령, 착복" },
      { "en": "embezzle", "ko": "횡령하다" },
      { "en": "bribery", "ko": "뇌물 수수" },
      { "en": "monopoly", "ko": "독점" },
      { "en": "antitrust", "ko": "독점 금지의" },
      { "en": "fair trade", "ko": "공정 무역" },
      { "en": "philanthropy", "ko": "자선 활동, 박애" },
      { "en": "philanthropist", "ko": "자선가" },
      { "en": "charity", "ko": "자선 단체, 자비" },
      { "en": "donation", "ko": "기부, 기증" },
      { "en": "donate", "ko": "기부하다" },
      { "en": "nonprofit", "ko": "비영리의, 비영리 단체" },
      { "en": "foundation", "ko": "재단" },
      { "en": "corporate citizenship", "ko": "기업 시민의식" },
      { "en": "sweatshop", "ko": "착취 공장" },
      { "en": "fair wage", "ko": "공정 임금" },
      { "en": "work-life balance", "ko": "일과 삶의 균형" },
      { "en": "maternity leave", "ko": "출산 휴가" },
      { "en": "paternity leave", "ko": "육아 휴직" },
      { "en": "harassment", "ko": "괴롭힘, 희롱" },
      { "en": "workplace safety", "ko": "직장 안전" },
      { "en": "ergonomics", "ko": "인간공학" },
      { "en": "ergonomic", "ko": "인간공학적인" },
      { "en": "job security", "ko": "고용 안정성" },
      { "en": "turnover rate", "ko": "이직률" },
      { "en": "absenteeism", "ko": "잦은 결근" },
      { "en": "morale", "ko": "사기, 의욕" },
      { "en": "synergy", "ko": "상승 효과, 시너지" },
      { "en": "core competency", "ko": "핵심 역량" }
    ]
  },
  {
    "id": "wm2000_day_49",
    "book": "워드마스터 수능 2000",
    "title": "Day 49",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "biodiversity", "ko": "생물다양성" },
      { "en": "biome", "ko": "생물군계" },
      { "en": "flora", "ko": "식물군" },
      { "en": "fauna", "ko": "동물군" },
      { "en": "indigenous", "ko": "토착의, 고유한" },
      { "en": "native", "ko": "토착의, 원주민" },
      { "en": "invasive species", "ko": "외래 침입종" },
      { "en": "ecological niche", "ko": "생태적 지위" },
      { "en": "food chain", "ko": "먹이 사슬" },
      { "en": "food web", "ko": "먹이 그물" },
      { "en": "trophic level", "ko": "영양 단계" },
      { "en": "predator", "ko": "포식자" },
      { "en": "prey", "ko": "먹이, 사냥감" },
      { "en": "predation", "ko": "포식, 포식 활동" },
      { "en": "symbiosis", "ko": "공생" },
      { "en": "symbiotic", "ko": "공생의" },
      { "en": "mutualism", "ko": "상리공생" },
      { "en": "parasitism", "ko": "기생" },
      { "en": "parasite", "ko": "기생충, 기생 동물" },
      { "en": "host", "ko": "숙주, 주최자" },
      { "en": "clone", "ko": "복제 생물, 복제하다" },
      { "en": "cloning", "ko": "생물 복제" },
      { "en": "genetic modification", "ko": "유전자 변형" },
      { "en": "transgenic", "ko": "유전자 이식의" },
      { "en": "stem cell", "ko": "줄기세포" },
      { "en": "crispr", "ko": "유전자 가위 기술" },
      { "en": "bioethics", "ko": "생명윤리" },
      { "en": "in vitro", "ko": "시험관 내에서의" },
      { "en": "in vivo", "ko": "생체 내에서의" },
      { "en": "specimen", "ko": "표본, 시료" },
      { "en": "taxidermy", "ko": "박제술" },
      { "en": "taxonomy", "ko": "분류학" },
      { "en": "genus", "ko": "속 (생물 분류)" },
      { "en": "phylum", "ko": "문 (생물 분류)" },
      { "en": "kingdom", "ko": "계 (생물 분류), 왕국" },
      { "en": "botany", "ko": "식물학" },
      { "en": "botanist", "ko": "식물학자" },
      { "en": "zoology", "ko": "동물학" },
      { "en": "zoologist", "ko": "동물학자" },
      { "en": "endangered species", "ko": "멸종 위기종" }
    ]
  },
  {
    "id": "wm2000_day_50",
    "book": "워드마스터 수능 2000",
    "title": "Day 50",
    "studentIds": [1, 2, 3, 4, 5, 6],
    "words": [
      { "en": "ubiquitous", "ko": "어디에나 존재하는, 보편적인" },
      { "en": "ephemeral", "ko": "수명이 짧은, 덧없는" },
      { "en": "quintessential", "ko": "전형적인, 본질적인" },
      { "en": "juxtaposition", "ko": "병치, 나란히 놓기" },
      { "en": "juxtapose", "ko": "나란히 놓다, 병치하다" },
      { "en": "idiosyncrasy", "ko": "특이한 성향, 별스러운 점" },
      { "en": "anomalous", "ko": "변칙의, 이례적인" },
      { "en": "anomaly", "ko": "변칙, 예외, 이례" },
      { "en": "dichotomy", "ko": "이분법, 양분" },
      { "en": "conundrum", "ko": "난제, 수수께끼" },
      { "en": "paradigm shift", "ko": "패러다임의 전환" },
      { "en": "status quo", "ko": "현재의 상태, 현상 유지" },
      { "en": "pragmatism", "ko": "실용주의" },
      { "en": "existential", "ko": "실존주의의, 존재에 관한" },
      { "en": "subjugate", "ko": "굴복시키다, 지배하다" },
      { "en": "exacerbate", "ko": "악화시키다" },
      { "en": "ameliorate", "ko": "개선하다, 완화하다" },
      { "en": "mitigate", "ko": "완화하다, 경감하다" },
      { "en": "proliferation", "ko": "급증, 확산" },
      { "en": "proliferate", "ko": "급증하다, 확산되다" },
      { "en": "omnipresent", "ko": "편재하는, 어디에나 있는" },
      { "en": "superfluous", "ko": "불필요한, 과잉의" },
      { "en": "counterintuitive", "ko": "직관에 반하는" },
      { "en": "pinnacle", "ko": "정점, 절정" },
      { "en": "nadir", "ko": "최악의 순간, 바닥" },
      { "en": "catalyst", "ko": "기폭제, 촉매" },
      { "en": "trajectory", "ko": "궤적, 궤도" },
      { "en": "zenith", "ko": "천정, 절정" },
      { "en": "precarious", "ko": "불안정한, 위태로운" },
      { "en": "tenuous", "ko": "미약한, 극도로 빈약한" },
      { "en": "resilience", "ko": "회복력, 탄력성" },
      { "en": "resilient", "ko": "회복력 있는, 탄력 있는" },
      { "en": "heterogeneous", "ko": "이질적인, 다양한" },
      { "en": "homogeneous", "ko": "동질적인, 균일한" },
      { "en": "quintessence", "ko": "진수, 본질" },
      { "en": "antithesis", "ko": "정반대, 대조" },
      { "en": "synthesize", "ko": "종합하다, 합성하다" },
      { "en": "synthesis", "ko": "종합, 합성" },
      { "en": "culmination", "ko": "정점, 최고조" },
      { "en": "culminate", "ko": "끝을 맺다, 최고조에 달하다" }
    ]
  }
];

if (typeof window !== "undefined") {
  window.WORDMASTER_2000_SETS = WORDMASTER_2000_SETS;
}
